const fs = require('fs')
    
module.exports = { QueenFont1, QueenFont2, QueenFont3, QueenFont4, QueenFont5, QueenFont6, QueenFont7, QueenFont8, QueenFont9, QueenFont10, QueenFont11, QueenFont12, QueenFont13, QueenFont14, QueenFont15, QueenFont16, QueenFont17, QueenFont18, QueenFont19, QueenFont20, QueenFont21, QueenFont22, QueenFont23, QueenFont24, QueenFont25, QueenFont26, QueenFont27, QueenFont28, QueenFont29, QueenFont30, QueenFont31, QueenFont32, QueenFont33, QueenFont34, QueenFont35, QueenFont36, QueenFont37, QueenFont38, QueenFont39 }

//if(!fs.existsSync('.//root/AlienQueen/lib/colab.js')) throw 'This Is Only For Alien-Queen Bot'


   function QueenFont1(textz) {  
     QueenFont = textz
        .replaceAll('a', '𝔞')
        .replaceAll('b', '𝔟')
        .replaceAll('c', '𝔠')
        .replaceAll('d', '𝔡')
        .replaceAll('e', '𝔢')
        .replaceAll('f', '𝔣')
        .replaceAll('g', '𝔤')
        .replaceAll('h', '𝔥')
        .replaceAll('i', '𝔦')
        .replaceAll('j', '𝔧')
        .replaceAll('k', '𝔨')
        .replaceAll('l', '𝔩')
        .replaceAll('m', '𝔪')
        .replaceAll('n', '𝔫')
        .replaceAll('o', '𝔬')
        .replaceAll('p', '𝔭')
        .replaceAll('q', '𝔮')
        .replaceAll('r', '𝔯')
        .replaceAll('s', '𝔰')
        .replaceAll('t', '𝔱')
        .replaceAll('u', '𝔲')
        .replaceAll('v', '𝔳')
        .replaceAll('w', '𝔴')
        .replaceAll('x', '𝔵')
        .replaceAll('y', '𝔶')
        .replaceAll('z', '𝔷')
        .replaceAll('A', '𝔄')
        .replaceAll('B', '𝔅')
        .replaceAll('C', 'ℭ')
        .replaceAll('D', '𝔇')
        .replaceAll('E', '𝔈')
        .replaceAll('F', '𝔉')
        .replaceAll('G', '𝔊')
        .replaceAll('H', 'ℌ')
        .replaceAll('I', 'ℑ')
        .replaceAll('J', '𝔍')
        .replaceAll('K', '𝔎')
        .replaceAll('L', '𝔏')
        .replaceAll('M', '𝔐')
        .replaceAll('N', '𝔑')
        .replaceAll('O', '𝔒')
        .replaceAll('P', '𝔓')
        .replaceAll('Q', '𝔔')
        .replaceAll('R', 'ℜ')
        .replaceAll('S', '𝔖')
        .replaceAll('T', '𝔗')
        .replaceAll('U', '𝔘')
        .replaceAll('V', '𝔙')
        .replaceAll('W', '𝔚')
        .replaceAll('X', '𝔛')
        .replaceAll('Y', '𝔜')
        .replaceAll('Z', 'ℨ');
return QueenFont        
        
      
  }

  function QueenFont2(textz) {  
    QueenFont = textz
        .replaceAll('0', '𝟶')
        .replaceAll('1', '𝟷')
        .replaceAll('2', '𝟸')
        .replaceAll('3', '𝟹')
        .replaceAll('4', '𝟺')
        .replaceAll('5', '𝟻')
        .replaceAll('6', '𝟼')
        .replaceAll('7', '𝟽')
        .replaceAll('8', '𝟾')
        .replaceAll('9', '𝟿')
        .replaceAll('a', '𝚊')
        .replaceAll('b', '𝚋')
        .replaceAll('c', '𝚌')
        .replaceAll('d', '𝚍')
        .replaceAll('e', '𝚎')
        .replaceAll('f', '𝚏')
        .replaceAll('g', '𝚐')
        .replaceAll('h', '𝚑')
        .replaceAll('i', '𝚒')
        .replaceAll('j', '𝚓')
        .replaceAll('k', '𝚔')
        .replaceAll('l', '𝚕')
        .replaceAll('m', '𝚖')
        .replaceAll('n', '𝚗')
        .replaceAll('o', '𝚘')
        .replaceAll('p', '𝚙')
        .replaceAll('q', '𝚚')
        .replaceAll('r', '𝚛')
        .replaceAll('s', '𝚜')
        .replaceAll('t', '𝚝')
        .replaceAll('u', '𝚞')
        .replaceAll('v', '𝚟')
        .replaceAll('w', '𝚠')
        .replaceAll('x', '𝚡')
        .replaceAll('y', '𝚢')
        .replaceAll('z', '𝚣')
        .replaceAll('A', '𝙰')
        .replaceAll('B', '𝙱')
        .replaceAll('C', '𝙲')
        .replaceAll('D', '𝙳')
        .replaceAll('E', '𝙴')
        .replaceAll('F', '𝙵')
        .replaceAll('G', '𝙶')
        .replaceAll('H', '𝙷')
        .replaceAll('I', '𝙸')
        .replaceAll('J', '𝙹')
        .replaceAll('K', '𝙺')
        .replaceAll('L', '𝙻')
        .replaceAll('M', '𝙼')
        .replaceAll('N', '𝙽')
        .replaceAll('O', '𝙾')
        .replaceAll('P', '𝙿')
        .replaceAll('Q', '𝚀')
        .replaceAll('R', '𝚁')
        .replaceAll('S', '𝚂')
        .replaceAll('T', '𝚃')
        .replaceAll('U', '𝚄')
        .replaceAll('V', '𝚅')
        .replaceAll('W', '𝚆')
        .replaceAll('X', '𝚇')
        .replaceAll('Y', '𝚈')
        .replaceAll('Z', '𝚉');
return QueenFont  
        
      
  }

 
  function QueenFont3(textz) {  
    QueenFont = textz
        .replaceAll('0', '0')
        .replaceAll('1', '1')
        .replaceAll('2', '2')
        .replaceAll('3', '3')
        .replaceAll('4', '4')
        .replaceAll('5', '5')
        .replaceAll('6', '6')
        .replaceAll('7', '7')
        .replaceAll('8', '8')
        .replaceAll('9', '9')
        .replaceAll('a', '𝙖')
        .replaceAll('b', '𝙗')
        .replaceAll('c', '𝙘')
        .replaceAll('d', '𝙙')
        .replaceAll('e', '𝙚')
        .replaceAll('f', '𝙛')
        .replaceAll('g', '𝙜')
        .replaceAll('h', '𝙝')
        .replaceAll('i', '𝙞')
        .replaceAll('j', '𝙟')
        .replaceAll('k', '𝙠')
        .replaceAll('l', '𝙡')
        .replaceAll('m', '𝙢')
        .replaceAll('n', '𝙣')
        .replaceAll('o', '𝙤')
        .replaceAll('p', '𝙥')
        .replaceAll('q', '𝙦')
        .replaceAll('r', '𝙧')
        .replaceAll('s', '𝙨')
        .replaceAll('t', '𝙩')
        .replaceAll('u', '𝙪')
        .replaceAll('v', '𝙫')
        .replaceAll('w', '𝙬')
        .replaceAll('x', '𝙭')
        .replaceAll('y', '𝙮')
        .replaceAll('z', '𝙯')
        .replaceAll('A', '𝘼')
        .replaceAll('B', '𝘽')
        .replaceAll('C', '𝘾')
        .replaceAll('D', '𝘿')
        .replaceAll('E', '𝙀')
        .replaceAll('F', '𝙁')
        .replaceAll('G', '𝙂')
        .replaceAll('H', '𝙃')
        .replaceAll('I', '𝙄')
        .replaceAll('J', '𝙅')
        .replaceAll('K', '𝙆')
        .replaceAll('L', '𝙇')
        .replaceAll('M', '𝙈')
        .replaceAll('N', '𝙉')
        .replaceAll('O', '𝙊')
        .replaceAll('P', '𝙋')
        .replaceAll('Q', '𝙌')
        .replaceAll('R', '𝙍')
        .replaceAll('S', '𝙎')
        .replaceAll('T', '𝙏')
        .replaceAll('U', '𝙐')
        .replaceAll('V', '𝙑')
        .replaceAll('W', '𝙒')
        .replaceAll('X', '𝙓')
        .replaceAll('Y', '𝙔')
        .replaceAll('Z', '𝙕');
return QueenFont  
        
      
  }


  function QueenFont4(textz) {  
    QueenFont = textz
        .replaceAll('0', '𝟎')
        .replaceAll('1', '𝟏')
        .replaceAll('2', '𝟐')
        .replaceAll('3', '𝟑')
        .replaceAll('4', '𝟒')
        .replaceAll('5', '𝟓')
        .replaceAll('6', '𝟔')
        .replaceAll('7', '𝟕')
        .replaceAll('8', '𝟖')
        .replaceAll('9', '𝟗')
        .replaceAll('a', '𝐚')
        .replaceAll('b', '𝐛')
        .replaceAll('c', '𝐜')
        .replaceAll('d', '𝐝')
        .replaceAll('e', '𝐞')
        .replaceAll('f', '𝐟')
        .replaceAll('g', '𝐠')
        .replaceAll('h', '𝐡')
        .replaceAll('i', '𝐢')
        .replaceAll('j', '𝐣')
        .replaceAll('k', '𝐤')
        .replaceAll('l', '𝐥')
        .replaceAll('m', '𝐦')
        .replaceAll('n', '𝐧')
        .replaceAll('o', '𝐨')
        .replaceAll('p', '𝐩')
        .replaceAll('q', '𝐪')
        .replaceAll('r', '𝐫')
        .replaceAll('s', '𝐬')
        .replaceAll('t', '𝐭')
        .replaceAll('u', '𝐮')
        .replaceAll('v', '𝐯')
        .replaceAll('w', '𝐰')
        .replaceAll('x', '𝐱')
        .replaceAll('y', '𝐲')
        .replaceAll('z', '𝐳')
        .replaceAll('A', '𝐀')
        .replaceAll('B', '𝐁')
        .replaceAll('C', '𝐂')
        .replaceAll('D', '𝐃')
        .replaceAll('E', '𝐄')
        .replaceAll('F', '𝐅')
        .replaceAll('G', '𝐆')
        .replaceAll('H', '𝐇')
        .replaceAll('I', '𝐈')
        .replaceAll('J', '𝐉')
        .replaceAll('K', '𝐊')
        .replaceAll('L', '𝐋')
        .replaceAll('M', '𝐌')
        .replaceAll('N', '𝐍')
        .replaceAll('O', '𝐎')
        .replaceAll('P', '𝐏')
        .replaceAll('Q', '𝐐')
        .replaceAll('R', '𝐑')
        .replaceAll('S', '𝐒')
        .replaceAll('T', '𝐓')
        .replaceAll('U', '𝐔')
        .replaceAll('V', '𝐕')
        .replaceAll('W', '𝐖')
        .replaceAll('X', '𝐗')
        .replaceAll('Y', '𝐘')
        .replaceAll('Z', '𝐙');
return QueenFont  
        
      
  }

 
  function QueenFont5(textz) {  
   QueenFont = textz
        .replaceAll('0', '𝟬')
        .replaceAll('1', '𝟭')
        .replaceAll('2', '𝟮')
        .replaceAll('3', '𝟯')
        .replaceAll('4', '𝟰')
        .replaceAll('5', '𝟱')
        .replaceAll('6', '𝟲')
        .replaceAll('7', '𝟳')
        .replaceAll('8', '𝟴')
        .replaceAll('9', '𝟵')
        .replaceAll('a', '𝗮')
        .replaceAll('b', '𝗯')
        .replaceAll('c', '𝗰')
        .replaceAll('d', '𝗱')
        .replaceAll('e', '𝗲')
        .replaceAll('f', '𝗳')
        .replaceAll('g', '𝗴')
        .replaceAll('h', '𝗵')
        .replaceAll('i', '𝗶')
        .replaceAll('j', '𝗷')
        .replaceAll('k', '𝗸')
        .replaceAll('l', '𝗹')
        .replaceAll('m', '𝗺')
        .replaceAll('n', '𝗻')
        .replaceAll('o', '𝗼')
        .replaceAll('p', '𝗽')
        .replaceAll('q', '𝗾')
        .replaceAll('r', '𝗿')
        .replaceAll('s', '𝘀')
        .replaceAll('t', '𝘁')
        .replaceAll('u', '𝘂')
        .replaceAll('v', '𝘃')
        .replaceAll('w', '𝘄')
        .replaceAll('x', '𝘅')
        .replaceAll('y', '𝘆')
        .replaceAll('z', '𝘇')
        .replaceAll('A', '𝗔')
        .replaceAll('B', '𝗕')
        .replaceAll('C', '𝗖')
        .replaceAll('D', '𝗗')
        .replaceAll('E', '𝗘')
        .replaceAll('F', '𝗙')
        .replaceAll('G', '𝗚')
        .replaceAll('H', '𝗛')
        .replaceAll('I', '𝗜')
        .replaceAll('J', '𝗝')
        .replaceAll('K', '𝗞')
        .replaceAll('L', '𝗟')
        .replaceAll('M', '𝗠')
        .replaceAll('N', '𝗡')
        .replaceAll('O', '𝗢')
        .replaceAll('P', '𝗣')
        .replaceAll('Q', '𝗤')
        .replaceAll('R', '𝗥')
        .replaceAll('S', '𝗦')
        .replaceAll('T', '𝗧')
        .replaceAll('U', '𝗨')
        .replaceAll('V', '𝗩')
        .replaceAll('W', '𝗪')
        .replaceAll('X', '𝗫')
        .replaceAll('Y', '𝗬')
        .replaceAll('Z', '𝗭');
return QueenFont  
        
      
  }

 function QueenFont6(textz) {  
   QueenFont = textz
        .replaceAll('0', '𝟘')
        .replaceAll('1', '𝟙')
        .replaceAll('2', '𝟚')
        .replaceAll('3', '𝟛')
        .replaceAll('4', '𝟜')
        .replaceAll('5', '𝟝')
        .replaceAll('6', '𝟞')
        .replaceAll('7', '𝟟')
        .replaceAll('8', '𝟠')
        .replaceAll('9', '𝟡')
        .replaceAll('a', '𝕒')
        .replaceAll('b', '𝕓')
        .replaceAll('c', '𝕔')
        .replaceAll('d', '𝕕')
        .replaceAll('e', '𝕖')
        .replaceAll('f', '𝕗')
        .replaceAll('g', '𝕘')
        .replaceAll('h', '𝕙')
        .replaceAll('i', '𝕚')
        .replaceAll('j', '𝕛')
        .replaceAll('k', '𝕜')
        .replaceAll('l', '𝕝')
        .replaceAll('m', '𝕞')
        .replaceAll('n', '𝕟')
        .replaceAll('o', '𝕠')
        .replaceAll('p', '𝕡')
        .replaceAll('q', '𝕢')
        .replaceAll('r', '𝕣')
        .replaceAll('s', '𝕤')
        .replaceAll('t', '𝕥')
        .replaceAll('u', '𝕦')
        .replaceAll('v', '𝕧')
        .replaceAll('w', '𝕨')
        .replaceAll('x', '𝕩')
        .replaceAll('y', '𝕪')
        .replaceAll('z', '𝕫')
        .replaceAll('A', '𝔸')
        .replaceAll('B', '𝔹')
        .replaceAll('C', 'ℂ')
        .replaceAll('D', '𝔻')
        .replaceAll('E', '𝔼')
        .replaceAll('F', '𝔽')
        .replaceAll('G', '𝔾')
        .replaceAll('H', 'ℍ')
        .replaceAll('I', '𝕀')
        .replaceAll('J', '𝕁')
        .replaceAll('K', '𝕂')
        .replaceAll('L', '𝕃')
        .replaceAll('M', '𝕄')
        .replaceAll('N', 'ℕ')
        .replaceAll('O', '𝕆')
        .replaceAll('P', 'ℙ')
        .replaceAll('Q', 'ℚ')
        .replaceAll('R', 'ℝ')
        .replaceAll('S', '𝕊')
        .replaceAll('T', '𝕋')
        .replaceAll('U', '𝕌')
        .replaceAll('V', '𝕍')
        .replaceAll('W', '𝕎')
        .replaceAll('X', '𝕏')
        .replaceAll('Y', '𝕐')
        .replaceAll('Z', 'ℤ'); 
        return QueenFont  
  }
              
  
  
      

function QueenFont7(textz) {  
   QueenFont = textz
        .replaceAll('0', '0')
        .replaceAll('1', '1')
        .replaceAll('2', '2')
        .replaceAll('3', '3')
        .replaceAll('4', '4')
        .replaceAll('5', '5')
        .replaceAll('6', '6')
        .replaceAll('7', '7')
        .replaceAll('8', '8')
        .replaceAll('9', '9')
        .replaceAll('a', '𝘢')
        .replaceAll('b', '𝘣')
        .replaceAll('c', '𝘤')
        .replaceAll('d', '𝘥')
        .replaceAll('e', '𝘦')
        .replaceAll('f', '𝘧')
        .replaceAll('g', '𝘨')
        .replaceAll('h', '𝘩')
        .replaceAll('i', '𝘪')
        .replaceAll('j', '𝘫')
        .replaceAll('k', '𝘬')
        .replaceAll('l', '𝘭')
        .replaceAll('m', '𝘮')
        .replaceAll('n', '𝘯')
        .replaceAll('o', '𝘰')
        .replaceAll('p', '𝘱')
        .replaceAll('q', '𝘲')
        .replaceAll('r', '𝘳')
        .replaceAll('s', '𝘴')
        .replaceAll('t', '𝘵')
        .replaceAll('u', '𝘶')
        .replaceAll('v', '𝘷')
        .replaceAll('w', '𝘸')
        .replaceAll('x', '𝘹')
        .replaceAll('y', '𝘺')
        .replaceAll('z', '𝘻')
        .replaceAll('A', '𝘈')
        .replaceAll('B', '𝘉')
        .replaceAll('C', '𝘊')
        .replaceAll('D', '𝘋')
        .replaceAll('E', '𝘌')
        .replaceAll('F', '𝘍')
        .replaceAll('G', '𝘎')
        .replaceAll('H', '𝘏')
        .replaceAll('I', '𝘐')
        .replaceAll('J', '𝘑')
        .replaceAll('K', '𝘒')
        .replaceAll('L', '𝘓')
        .replaceAll('M', '𝘔')
        .replaceAll('N', '𝘕')
        .replaceAll('O', '𝘖')
        .replaceAll('P', '𝘗')
        .replaceAll('Q', '𝘘')
        .replaceAll('R', '𝘙')
        .replaceAll('S', '𝘚')
        .replaceAll('T', '𝘛')
        .replaceAll('U', '𝘜')
        .replaceAll('V', '𝘝')
        .replaceAll('W', '𝘞')
        .replaceAll('X', '𝘟')
        .replaceAll('Y', '𝘠')
        .replaceAll('Z', '𝘡');
return QueenFont  }


  function QueenFont8(textz)  {
     QueenFont = textz
        .replaceAll('a', 'ᴀ')
        .replaceAll('b', 'ʙ')
        .replaceAll('c', 'ᴄ')
        .replaceAll('d', 'ᴅ')
        .replaceAll('e', 'ᴇ')
        .replaceAll('f', 'ғ')
        .replaceAll('g', 'ɢ')
        .replaceAll('h', 'ʜ')
        .replaceAll('i', 'ɪ')
        .replaceAll('j', 'ᴊ')
        .replaceAll('k', 'ᴋ')
        .replaceAll('l', 'ʟ')
        .replaceAll('m', 'ᴍ')
        .replaceAll('n', 'ɴ')
        .replaceAll('o', 'ᴏ')
        .replaceAll('p', 'ᴘ')
        .replaceAll('q', 'ǫ')
        .replaceAll('r', 'ʀ')
        .replaceAll('s', 's')
        .replaceAll('t', 'ᴛ')
        .replaceAll('u', 'ᴜ')
        .replaceAll('v', 'ᴠ')
        .replaceAll('w', 'ᴡ')
        .replaceAll('x', 'x')
        .replaceAll('y', 'ʏ')
        .replaceAll('z', 'ᴢ')
        .replaceAll('A', 'ᴀ')
        .replaceAll('B', 'ʙ')
        .replaceAll('C', 'ᴄ')
        .replaceAll('D', 'ᴅ')
        .replaceAll('E', 'ᴇ')
        .replaceAll('F', 'ғ')
        .replaceAll('G', 'ɢ')
        .replaceAll('H', 'ʜ')
        .replaceAll('I', 'ɪ')
        .replaceAll('J', 'ᴊ')
        .replaceAll('K', 'ᴋ')
        .replaceAll('L', 'ʟ')
        .replaceAll('M', 'ᴍ')
        .replaceAll('N', 'ɴ')
        .replaceAll('O', 'ᴏ')
        .replaceAll('P', 'ᴘ')
        .replaceAll('Q', 'ǫ')
        .replaceAll('R', 'ʀ')
        .replaceAll('S', 's')
        .replaceAll('T', 'ᴛ')
        .replaceAll('U', 'ᴜ')
        .replaceAll('V', 'ᴠ')
        .replaceAll('W', 'ᴡ')
        .replaceAll('X', 'x')
        .replaceAll('Y', 'ʏ')
        .replaceAll('Z', 'ᴢ');
return QueenFont  }
              
  
  
      
        
      
      
  
      
     //function QueenFont9(textz)  {
       
  function QueenFont9(textz)  {  
     QueenFont = textz
        .replaceAll('0', '0')
        .replaceAll('1', '1')
        .replaceAll('2', '2')
        .replaceAll('3', '3')
        .replaceAll('4', '4')
        .replaceAll('5', '5')
        .replaceAll('6', '6')
        .replaceAll('7', '7')
        .replaceAll('8', '8')
        .replaceAll('9', '9')
        .replaceAll('a', 'ค')
        .replaceAll('b', '๖')
        .replaceAll('c', '¢')
        .replaceAll('d', '໓')
        .replaceAll('e', 'ē')
        .replaceAll('f', 'f')
        .replaceAll('g', 'ງ')
        .replaceAll('h', 'h')
        .replaceAll('i', 'i')
        .replaceAll('j', 'ว')
        .replaceAll('k', 'k')
        .replaceAll('l', 'l')
        .replaceAll('m', '๓')
        .replaceAll('n', 'ຖ')
        .replaceAll('o', '໐')
        .replaceAll('p', 'p')
        .replaceAll('q', '๑')
        .replaceAll('r', 'r')
        .replaceAll('s', 'Ş')
        .replaceAll('t', 't')
        .replaceAll('u', 'น')
        .replaceAll('v', 'ง')
        .replaceAll('w', 'ຟ')
        .replaceAll('x', 'x')
        .replaceAll('y', 'ฯ')
        .replaceAll('z', 'ຊ')
        .replaceAll('A', 'ค')
        .replaceAll('B', '๖')
        .replaceAll('C', '¢')
        .replaceAll('D', '໓')
        .replaceAll('E', 'ē')
        .replaceAll('F', 'f')
        .replaceAll('G', 'ງ')
        .replaceAll('H', 'h')
        .replaceAll('I', 'i')
        .replaceAll('J', 'ว')
        .replaceAll('K', 'k')
        .replaceAll('L', 'l')
        .replaceAll('M', '๓')
        .replaceAll('N', 'ຖ')
        .replaceAll('O', '໐')
        .replaceAll('P', 'p')
        .replaceAll('Q', '๑')
        .replaceAll('R', 'r')
        .replaceAll('S', 'Ş')
        .replaceAll('T', 't')
        .replaceAll('U', 'น')
        .replaceAll('V', 'ง')
        .replaceAll('W', 'ຟ')
        .replaceAll('X', 'x')
        .replaceAll('Y', 'ฯ')
        .replaceAll('Z', 'ຊ');
return QueenFont  
        
      
  }
              
  
  
      

      
      
       
  function QueenFont10(textz)  {  
     QueenFont = textz
        .replaceAll('0', '0')
        .replaceAll('1', '1')
        .replaceAll('2', '2')
        .replaceAll('3', '3')
        .replaceAll('4', '4')
        .replaceAll('5', '5')
        .replaceAll('6', '6')
        .replaceAll('7', '7')
        .replaceAll('8', '8')
        .replaceAll('9', '9')
        .replaceAll('a', 'ą')
        .replaceAll('b', 'ც')
        .replaceAll('c', 'ƈ')
        .replaceAll('d', 'ɖ')
        .replaceAll('e', 'ɛ')
        .replaceAll('f', 'ʄ')
        .replaceAll('g', 'ɠ')
        .replaceAll('h', 'ɧ')
        .replaceAll('i', 'ı')
        .replaceAll('j', 'ʝ')
        .replaceAll('k', 'ƙ')
        .replaceAll('l', 'Ɩ')
        .replaceAll('m', 'ɱ')
        .replaceAll('n', 'ŋ')
        .replaceAll('o', 'ơ')
        .replaceAll('p', '℘')
        .replaceAll('q', 'զ')
        .replaceAll('r', 'ཞ')
        .replaceAll('s', 'ʂ')
        .replaceAll('t', 'ɬ')
        .replaceAll('u', 'ų')
        .replaceAll('v', '۷')
        .replaceAll('w', 'ῳ')
        .replaceAll('x', 'ҳ')
        .replaceAll('y', 'ყ')
        .replaceAll('z', 'ʑ')
        .replaceAll('A', 'ą')
        .replaceAll('B', 'ც')
        .replaceAll('C', 'ƈ')
        .replaceAll('D', 'ɖ')
        .replaceAll('E', 'ɛ')
        .replaceAll('F', 'ʄ')
        .replaceAll('G', 'ɠ')
        .replaceAll('H', 'ɧ')
        .replaceAll('I', 'ı')
        .replaceAll('J', 'ʝ')
        .replaceAll('K', 'ƙ')
        .replaceAll('L', 'Ɩ')
        .replaceAll('M', 'ɱ')
        .replaceAll('N', 'ŋ')
        .replaceAll('O', 'ơ')
        .replaceAll('P', '℘')
        .replaceAll('Q', 'զ')
        .replaceAll('R', 'ཞ')
        .replaceAll('S', 'ʂ')
        .replaceAll('T', 'ɬ')
        .replaceAll('U', 'ų')
        .replaceAll('V', '۷')
        .replaceAll('W', 'ῳ')
        .replaceAll('X', 'ҳ')
        .replaceAll('Y', 'ყ')
        .replaceAll('Z', 'ʑ');
return QueenFont  
        
      
  }
              
  
  
  
      
     
       
  function QueenFont11(textz)  {  
     QueenFont = textz
        .replaceAll('0', '0')
        .replaceAll('1', '1')
        .replaceAll('2', '2')
        .replaceAll('3', '3')
        .replaceAll('4', '4')
        .replaceAll('5', '5')
        .replaceAll('6', '6')
        .replaceAll('7', '7')
        .replaceAll('8', '8')
        .replaceAll('9', '9')
        .replaceAll('a', 'ﾑ')
        .replaceAll('b', '乃')
        .replaceAll('c', 'ᄃ')
        .replaceAll('d', 'り')
        .replaceAll('e', '乇')
        .replaceAll('f', 'ｷ')
        .replaceAll('g', 'ム')
        .replaceAll('h', 'ん')
        .replaceAll('i', 'ﾉ')
        .replaceAll('j', 'ﾌ')
        .replaceAll('k', 'ズ')
        .replaceAll('l', 'ﾚ')
        .replaceAll('m', 'ﾶ')
        .replaceAll('n', '刀')
        .replaceAll('o', 'の')
        .replaceAll('p', 'ｱ')
        .replaceAll('q', 'ゐ')
        .replaceAll('r', '尺')
        .replaceAll('s', '丂')
        .replaceAll('t', 'ｲ')
        .replaceAll('u', 'ひ')
        .replaceAll('v', '√')
        .replaceAll('w', 'W')
        .replaceAll('x', 'ﾒ')
        .replaceAll('y', 'ﾘ')
        .replaceAll('z', '乙')
        .replaceAll('A', 'ﾑ')
        .replaceAll('B', '乃')
        .replaceAll('C', 'ᄃ')
        .replaceAll('D', 'り')
        .replaceAll('E', '乇')
        .replaceAll('F', 'ｷ')
        .replaceAll('G', 'ム')
        .replaceAll('H', 'ん')
        .replaceAll('I', 'ﾉ')
        .replaceAll('J', 'ﾌ')
        .replaceAll('K', 'ズ')
        .replaceAll('L', 'ﾚ')
        .replaceAll('M', 'ﾶ')
        .replaceAll('N', '刀')
        .replaceAll('O', 'の')
        .replaceAll('P', 'ｱ')
        .replaceAll('Q', 'ゐ')
        .replaceAll('R', '尺')
        .replaceAll('S', '丂')
        .replaceAll('T', 'ｲ')
        .replaceAll('U', 'ひ')
        .replaceAll('V', '√')
        .replaceAll('W', 'W')
        .replaceAll('X', 'ﾒ')
        .replaceAll('Y', 'ﾘ')
        .replaceAll('Z', '乙');
return QueenFont  
        
      
  }
              
  
  
      
        
      
      
      
      
      //|⬡═══════════════════// 12 //══════════════════════|❝ Ⓒ𝙰𝙻𝙸𝙴𝙽 𝙰𝙻𝙵𝙰 𝙱𝙾𝚃 𝙱𝚈 𝚃𝙾𝚇𝙸𝙲 𝙰𝙻𝙸𝙴𝙽™ ❞|═══════════════════════════════════════════⬡|//	

  function QueenFont12(textz)  {  
     QueenFont = textz
        .replaceAll('0', '0')
        .replaceAll('1', '1')
        .replaceAll('2', '2')
        .replaceAll('3', '3')
        .replaceAll('4', '4')
        .replaceAll('5', '5')
        .replaceAll('6', '6')
        .replaceAll('7', '7')
        .replaceAll('8', '8')
        .replaceAll('9', '9')
        .replaceAll('a', '卂')
        .replaceAll('b', '乃')
        .replaceAll('c', '匚')
        .replaceAll('d', 'ᗪ')
        .replaceAll('e', '乇')
        .replaceAll('f', '千')
        .replaceAll('g', 'Ꮆ')
        .replaceAll('h', '卄')
        .replaceAll('i', '丨')
        .replaceAll('j', 'ﾌ')
        .replaceAll('k', 'Ҝ')
        .replaceAll('l', 'ㄥ')
        .replaceAll('m', '爪')
        .replaceAll('n', '几')
        .replaceAll('o', 'ㄖ')
        .replaceAll('p', '卩')
        .replaceAll('q', 'Ɋ')
        .replaceAll('r', '尺')
        .replaceAll('s', '丂')
        .replaceAll('t', 'ㄒ')
        .replaceAll('u', 'ㄩ')
        .replaceAll('v', 'ᐯ')
        .replaceAll('w', '山')
        .replaceAll('x', '乂')
        .replaceAll('y', 'ㄚ')
        .replaceAll('z', '乙')
        .replaceAll('A', '卂')
        .replaceAll('B', '乃')
        .replaceAll('C', '匚')
        .replaceAll('D', 'ᗪ')
        .replaceAll('E', '乇')
        .replaceAll('F', '千')
        .replaceAll('G', 'Ꮆ')
        .replaceAll('H', '卄')
        .replaceAll('I', '丨')
        .replaceAll('J', 'ﾌ')
        .replaceAll('K', 'Ҝ')
        .replaceAll('L', 'ㄥ')
        .replaceAll('M', '爪')
        .replaceAll('N', '几')
        .replaceAll('O', 'ㄖ')
        .replaceAll('P', '卩')
        .replaceAll('Q', 'Ɋ')
        .replaceAll('R', '尺')
        .replaceAll('S', '丂')
        .replaceAll('T', 'ㄒ')
        .replaceAll('U', 'ㄩ')
        .replaceAll('V', 'ᐯ')
        .replaceAll('W', '山')
        .replaceAll('X', '乂')
        .replaceAll('Y', 'ㄚ')
        .replaceAll('Z', '乙');
return QueenFont  
  }

      //|⬡═══════════════════// 13 //══════════════════════|❝ Ⓒ𝙰𝙻𝙸𝙴𝙽 𝙰𝙻𝙵𝙰 𝙱𝙾𝚃 𝙱𝚈 𝚃𝙾𝚇𝙸𝙲 𝙰𝙻𝙸𝙴𝙽™ ❞|═══════════════════════════════════════════⬡|//	

  function QueenFont13(textz)  {  
     QueenFont = textz
        .replaceAll('0', '0')
        .replaceAll('1', '1')
        .replaceAll('2', '2')
        .replaceAll('3', '3')
        .replaceAll('4', '4')
        .replaceAll('5', '5')
        .replaceAll('6', '6')
        .replaceAll('7', '7')
        .replaceAll('8', '8')
        .replaceAll('9', '9')
        .replaceAll('a', '🄰')
        .replaceAll('b', '🄱')
        .replaceAll('c', '🄲')
        .replaceAll('d', '🄳')
        .replaceAll('e', '🄴')
        .replaceAll('f', '🄵')
        .replaceAll('g', '🄶')
        .replaceAll('h', '🄷')
        .replaceAll('i', '🄸')
        .replaceAll('j', '🄹')
        .replaceAll('k', '🄺')
        .replaceAll('l', '🄻')
        .replaceAll('m', '🄼')
        .replaceAll('n', '🄽')
        .replaceAll('o', '🄾')
        .replaceAll('p', '🄿')
        .replaceAll('q', '🅀')
        .replaceAll('r', '🅁')
        .replaceAll('s', '🅂')
        .replaceAll('t', '🅃')
        .replaceAll('u', '🅄')
        .replaceAll('v', '🅅')
        .replaceAll('w', '🅆')
        .replaceAll('x', '🅇')
        .replaceAll('y', '🅈')
        .replaceAll('z', '🅉')
        .replaceAll('A', '🄰')
        .replaceAll('B', '🄱')
        .replaceAll('C', '🄲')
        .replaceAll('D', '🄳')
        .replaceAll('E', '🄴')
        .replaceAll('F', '🄵')
        .replaceAll('G', '🄶')
        .replaceAll('H', '🄷')
        .replaceAll('I', '🄸')
        .replaceAll('J', '🄹')
        .replaceAll('K', '🄺')
        .replaceAll('L', '🄻')
        .replaceAll('M', '🄼')
        .replaceAll('N', '🄽')
        .replaceAll('O', '🄾')
        .replaceAll('P', '🄿')
        .replaceAll('Q', '🅀')
        .replaceAll('R', '🅁')
        .replaceAll('S', '🅂')
        .replaceAll('T', '🅃')
        .replaceAll('U', '🅄')
        .replaceAll('V', '🅅')
        .replaceAll('W', '🅆')
        .replaceAll('X', '🅇')
        .replaceAll('Y', '🅈')
        .replaceAll('Z', '🅉');
return QueenFont  
        
      
  }

      //|⬡═══════════════════// 14 //══════════════════════|❝ Ⓒ𝙰𝙻𝙸𝙴𝙽 𝙰𝙻𝙵𝙰 𝙱𝙾𝚃 𝙱𝚈 𝚃𝙾𝚇𝙸𝙲 𝙰𝙻𝙸𝙴𝙽™ ❞|═══════════════════════════════════════════⬡|//	

  function QueenFont14(textz)  {  
     QueenFont = textz
        .replaceAll('0', '0')
        .replaceAll('1', '1')
        .replaceAll('2', '2')
        .replaceAll('3', '3')
        .replaceAll('4', '4')
        .replaceAll('5', '5')
        .replaceAll('6', '6')
        .replaceAll('7', '7')
        .replaceAll('8', '8')
        .replaceAll('9', '9')
        .replaceAll('a', 'Ꮧ')
        .replaceAll('b', 'Ᏸ')
        .replaceAll('c', 'ፈ')
        .replaceAll('d', 'Ꮄ')
        .replaceAll('e', 'Ꮛ')
        .replaceAll('f', 'Ꭶ')
        .replaceAll('g', 'Ꮆ')
        .replaceAll('h', 'Ꮒ')
        .replaceAll('i', 'Ꭵ')
        .replaceAll('j', 'Ꮰ')
        .replaceAll('k', 'Ꮶ')
        .replaceAll('l', 'Ꮭ')
        .replaceAll('m', 'Ꮇ')
        .replaceAll('n', 'Ꮑ')
        .replaceAll('o', 'Ꭷ')
        .replaceAll('p', 'Ꭾ')
        .replaceAll('q', 'Ꭴ')
        .replaceAll('r', 'Ꮢ')
        .replaceAll('s', 'Ꮥ')
        .replaceAll('t', 'Ꮦ')
        .replaceAll('u', 'Ꮼ')
        .replaceAll('v', 'Ꮙ')
        .replaceAll('w', 'Ꮗ')
        .replaceAll('x', 'ጀ')
        .replaceAll('y', 'Ꭹ')
        .replaceAll('z', 'ፚ')
        .replaceAll('A', 'Ꮧ')
        .replaceAll('B', 'Ᏸ')
        .replaceAll('C', 'ፈ')
        .replaceAll('D', 'Ꮄ')
        .replaceAll('E', 'Ꮛ')
        .replaceAll('F', 'Ꭶ')
        .replaceAll('G', 'Ꮆ')
        .replaceAll('H', 'Ꮒ')
        .replaceAll('I', 'Ꭵ')
        .replaceAll('J', 'Ꮰ')
        .replaceAll('K', 'Ꮶ')
        .replaceAll('L', 'Ꮭ')
        .replaceAll('M', 'Ꮇ')
        .replaceAll('N', 'Ꮑ')
        .replaceAll('O', 'Ꭷ')
        .replaceAll('P', 'Ꭾ')
        .replaceAll('Q', 'Ꭴ')
        .replaceAll('R', 'Ꮢ')
        .replaceAll('S', 'Ꮥ')
        .replaceAll('T', 'Ꮦ')
        .replaceAll('U', 'Ꮼ')
        .replaceAll('V', 'Ꮙ')
        .replaceAll('W', 'Ꮗ')
        .replaceAll('X', 'ጀ')
        .replaceAll('Y', 'Ꭹ')
        .replaceAll('Z', 'ፚ');
return QueenFont  
        
      
  }

      //|⬡═══════════════════// 15 //══════════════════════|❝ Ⓒ𝙰𝙻𝙸𝙴𝙽 𝙰𝙻𝙵𝙰 𝙱𝙾𝚃 𝙱𝚈 𝚃𝙾𝚇𝙸𝙲 𝙰𝙻𝙸𝙴𝙽™ ❞|═══════════════════════════════════════════⬡|//	

  function QueenFont15(textz)  {  
     QueenFont = textz
        .replaceAll('0', '0')
        .replaceAll('1', '1')
        .replaceAll('2', '2')
        .replaceAll('3', '3')
        .replaceAll('4', '4')
        .replaceAll('5', '5')
        .replaceAll('6', '6')
        .replaceAll('7', '7')
        .replaceAll('8', '8')
        .replaceAll('9', '9')
        .replaceAll('a', 'ᗩ')
        .replaceAll('b', 'ᗷ')
        .replaceAll('c', 'ᑕ')
        .replaceAll('d', 'ᗪ')
        .replaceAll('e', 'E')
        .replaceAll('f', 'ᖴ')
        .replaceAll('g', 'G')
        .replaceAll('h', 'ᕼ')
        .replaceAll('i', 'I')
        .replaceAll('j', 'ᒍ')
        .replaceAll('k', 'K')
        .replaceAll('l', 'ᒪ')
        .replaceAll('m', 'ᗰ')
        .replaceAll('n', 'ᑎ')
        .replaceAll('o', 'O')
        .replaceAll('p', 'ᑭ')
        .replaceAll('q', 'ᑫ')
        .replaceAll('r', 'ᖇ')
        .replaceAll('s', 'ᔕ')
        .replaceAll('t', 'T')
        .replaceAll('u', 'ᑌ')
        .replaceAll('v', 'ᐯ')
        .replaceAll('w', 'ᗯ')
        .replaceAll('x', '᙭')
        .replaceAll('y', 'Y')
        .replaceAll('z', 'ᘔ')
        .replaceAll('A', 'ᗩ')
        .replaceAll('B', 'ᗷ')
        .replaceAll('C', 'ᑕ')
        .replaceAll('D', 'ᗪ')
        .replaceAll('E', 'E')
        .replaceAll('F', 'ᖴ')
        .replaceAll('G', 'G')
        .replaceAll('H', 'ᕼ')
        .replaceAll('I', 'I')
        .replaceAll('J', 'ᒍ')
        .replaceAll('K', 'K')
        .replaceAll('L', 'ᒪ')
        .replaceAll('M', 'ᗰ')
        .replaceAll('N', 'ᑎ')
        .replaceAll('O', 'O')
        .replaceAll('P', 'ᑭ')
        .replaceAll('Q', 'ᑫ')
        .replaceAll('R', 'ᖇ')
        .replaceAll('S', 'ᔕ')
        .replaceAll('T', 'T')
        .replaceAll('U', 'ᑌ')
        .replaceAll('V', 'ᐯ')
        .replaceAll('W', 'ᗯ')
        .replaceAll('X', '᙭')
        .replaceAll('Y', 'Y')
        .replaceAll('Z', 'ᘔ');
return QueenFont  
        
      
  }

      //|⬡═══════════════════// 16 //══════════════════════|❝ Ⓒ𝙰𝙻𝙸𝙴𝙽 𝙰𝙻𝙵𝙰 𝙱𝙾𝚃 𝙱𝚈 𝚃𝙾𝚇𝙸𝙲 𝙰𝙻𝙸𝙴𝙽™ ❞|═══════════════════════════════════════════⬡|//	

  function QueenFont16(textz)  {  
     QueenFont = textz
        .replaceAll('0', '0')
        .replaceAll('1', '1')
        .replaceAll('2', '2')
        .replaceAll('3', '3')
        .replaceAll('4', '4')
        .replaceAll('5', '5')
        .replaceAll('6', '6')
        .replaceAll('7', '7')
        .replaceAll('8', '8')
        .replaceAll('9', '9')
        .replaceAll('a', 'ǟ')
        .replaceAll('b', 'ɮ')
        .replaceAll('c', 'ƈ')
        .replaceAll('d', 'ɖ')
        .replaceAll('e', 'ɛ')
        .replaceAll('f', 'ʄ')
        .replaceAll('g', 'ɢ')
        .replaceAll('h', 'ɦ')
        .replaceAll('i', 'ɨ')
        .replaceAll('j', 'ʝ')
        .replaceAll('k', 'ӄ')
        .replaceAll('l', 'ʟ')
        .replaceAll('m', 'ʍ')
        .replaceAll('n', 'ռ')
        .replaceAll('o', 'օ')
        .replaceAll('p', 'ք')
        .replaceAll('q', 'զ')
        .replaceAll('r', 'ʀ')
        .replaceAll('s', 'ֆ')
        .replaceAll('t', 'ȶ')
        .replaceAll('u', 'ʊ')
        .replaceAll('v', 'ʋ')
        .replaceAll('w', 'ա')
        .replaceAll('x', 'Ӽ')
        .replaceAll('y', 'ʏ')
        .replaceAll('z', 'ʐ')
        .replaceAll('A', 'ǟ')
        .replaceAll('B', 'ɮ')
        .replaceAll('C', 'ƈ')
        .replaceAll('D', 'ɖ')
        .replaceAll('E', 'ɛ')
        .replaceAll('F', 'ʄ')
        .replaceAll('G', 'ɢ')
        .replaceAll('H', 'ɦ')
        .replaceAll('I', 'ɨ')
        .replaceAll('J', 'ʝ')
        .replaceAll('K', 'ӄ')
        .replaceAll('L', 'ʟ')
        .replaceAll('M', 'ʍ')
        .replaceAll('N', 'ռ')
        .replaceAll('O', 'օ')
        .replaceAll('P', 'ք')
        .replaceAll('Q', 'զ')
        .replaceAll('R', 'ʀ')
        .replaceAll('S', 'ֆ')
        .replaceAll('T', 'ȶ')
        .replaceAll('U', 'ʊ')
        .replaceAll('V', 'ʋ')
        .replaceAll('W', 'ա')
        .replaceAll('X', 'Ӽ')
        .replaceAll('Y', 'ʏ')
        .replaceAll('Z', 'ʐ');
return QueenFont  
        
      
  }

      //|⬡═══════════════════// 17 //══════════════════════|❝ Ⓒ𝙰𝙻𝙸𝙴𝙽 𝙰𝙻𝙵𝙰 𝙱𝙾𝚃 𝙱𝚈 𝚃𝙾𝚇𝙸𝙲 𝙰𝙻𝙸𝙴𝙽™ ❞|═══════════════════════════════════════════⬡|//	

  function QueenFont17(textz)  {  
     QueenFont = textz
        .replaceAll('0', '𝟶')
        .replaceAll('1', '𝟷')
        .replaceAll('2', '𝟸')
        .replaceAll('3', '𝟹')
        .replaceAll('4', '𝟺')
        .replaceAll('5', '𝟻')
        .replaceAll('6', '𝟼')
        .replaceAll('7', '𝟽')
        .replaceAll('8', '𝟾')
        .replaceAll('9', '𝟿')
        .replaceAll('a', '𝚊')
        .replaceAll('b', '𝚋')
        .replaceAll('c', '𝚌')
        .replaceAll('d', '𝚍')
        .replaceAll('e', '𝚎')
        .replaceAll('f', '𝚏')
        .replaceAll('g', '𝚐')
        .replaceAll('h', '𝚑')
        .replaceAll('i', '𝚒')
        .replaceAll('j', '𝚓')
        .replaceAll('k', '𝚔')
        .replaceAll('l', '𝚕')
        .replaceAll('m', '𝚖')
        .replaceAll('n', '𝚗')
        .replaceAll('o', '𝚘')
        .replaceAll('p', '𝚙')
        .replaceAll('q', '𝚚')
        .replaceAll('r', '𝚛')
        .replaceAll('s', '𝚜')
        .replaceAll('t', '𝚝')
        .replaceAll('u', '𝚞')
        .replaceAll('v', '𝚟')
        .replaceAll('w', '𝚠')
        .replaceAll('x', '𝚡')
        .replaceAll('y', '𝚢')
        .replaceAll('z', '𝚣')
        .replaceAll('A', '𝙰')
        .replaceAll('B', '𝙱')
        .replaceAll('C', '𝙲')
        .replaceAll('D', '𝙳')
        .replaceAll('E', '𝙴')
        .replaceAll('F', '𝙵')
        .replaceAll('G', '𝙶')
        .replaceAll('H', '𝙷')
        .replaceAll('I', '𝙸')
        .replaceAll('J', '𝙹')
        .replaceAll('K', '𝙺')
        .replaceAll('L', '𝙻')
        .replaceAll('M', '𝙼')
        .replaceAll('N', '𝙽')
        .replaceAll('O', '𝙾')
        .replaceAll('P', '𝙿')
        .replaceAll('Q', '𝚀')
        .replaceAll('R', '𝚁')
        .replaceAll('S', '𝚂')
        .replaceAll('T', '𝚃')
        .replaceAll('U', '𝚄')
        .replaceAll('V', '𝚅')
        .replaceAll('W', '𝚆')
        .replaceAll('X', '𝚇')
        .replaceAll('Y', '𝚈')
        .replaceAll('Z', '𝚉');
return QueenFont  
        
      
  }

        //|⬡═══════════════════// 18 //══════════════════════|❝ Ⓒ𝙰𝙻𝙸𝙴𝙽 𝙰𝙻𝙵𝙰 𝙱𝙾𝚃 𝙱𝚈 𝚃𝙾𝚇𝙸𝙲 𝙰𝙻𝙸𝙴𝙽™ ❞|═══════════════════════════════════════════⬡|//	

  function QueenFont18(textz)  {  
     QueenFont = textz
        .replaceAll('0', '0')
        .replaceAll('1', '1')
        .replaceAll('2', '2')
        .replaceAll('3', '3')
        .replaceAll('4', '4')
        .replaceAll('5', '5')
        .replaceAll('6', '6')
        .replaceAll('7', '7')
        .replaceAll('8', '8')
        .replaceAll('9', '9')
        .replaceAll('a', '𝙖')
        .replaceAll('b', '𝙗')
        .replaceAll('c', '𝙘')
        .replaceAll('d', '𝙙')
        .replaceAll('e', '𝙚')
        .replaceAll('f', '𝙛')
        .replaceAll('g', '𝙜')
        .replaceAll('h', '𝙝')
        .replaceAll('i', '𝙞')
        .replaceAll('j', '𝙟')
        .replaceAll('k', '𝙠')
        .replaceAll('l', '𝙡')
        .replaceAll('m', '𝙢')
        .replaceAll('n', '𝙣')
        .replaceAll('o', '𝙤')
        .replaceAll('p', '𝙥')
        .replaceAll('q', '𝙦')
        .replaceAll('r', '𝙧')
        .replaceAll('s', '𝙨')
        .replaceAll('t', '𝙩')
        .replaceAll('u', '𝙪')
        .replaceAll('v', '𝙫')
        .replaceAll('w', '𝙬')
        .replaceAll('x', '𝙭')
        .replaceAll('y', '𝙮')
        .replaceAll('z', '𝙯')
        .replaceAll('A', '𝘼')
        .replaceAll('B', '𝘽')
        .replaceAll('C', '𝘾')
        .replaceAll('D', '𝘿')
        .replaceAll('E', '𝙀')
        .replaceAll('F', '𝙁')
        .replaceAll('G', '𝙂')
        .replaceAll('H', '𝙃')
        .replaceAll('I', '𝙄')
        .replaceAll('J', '𝙅')
        .replaceAll('K', '𝙆')
        .replaceAll('L', '𝙇')
        .replaceAll('M', '𝙈')
        .replaceAll('N', '𝙉')
        .replaceAll('O', '𝙊')
        .replaceAll('P', '𝙋')
        .replaceAll('Q', '𝙌')
        .replaceAll('R', '𝙍')
        .replaceAll('S', '𝙎')
        .replaceAll('T', '𝙏')
        .replaceAll('U', '𝙐')
        .replaceAll('V', '𝙑')
        .replaceAll('W', '𝙒')
        .replaceAll('X', '𝙓')
        .replaceAll('Y', '𝙔')
        .replaceAll('Z', '𝙕');
return QueenFont  
        
      
  }

      //|⬡═══════════════════// 19 //══════════════════════|❝ Ⓒ𝙰𝙻𝙸𝙴𝙽 𝙰𝙻𝙵𝙰 𝙱𝙾𝚃 𝙱𝚈 𝚃𝙾𝚇𝙸𝙲 𝙰𝙻𝙸𝙴𝙽™ ❞|═══════════════════════════════════════════⬡|//	

  function QueenFont19(textz)  {  
     QueenFont = textz
        .replaceAll('0', '𝟎')
        .replaceAll('1', '𝟏')
        .replaceAll('2', '𝟐')
        .replaceAll('3', '𝟑')
        .replaceAll('4', '𝟒')
        .replaceAll('5', '𝟓')
        .replaceAll('6', '𝟔')
        .replaceAll('7', '𝟕')
        .replaceAll('8', '𝟖')
        .replaceAll('9', '𝟗')
        .replaceAll('a', '𝐚')
        .replaceAll('b', '𝐛')
        .replaceAll('c', '𝐜')
        .replaceAll('d', '𝐝')
        .replaceAll('e', '𝐞')
        .replaceAll('f', '𝐟')
        .replaceAll('g', '𝐠')
        .replaceAll('h', '𝐡')
        .replaceAll('i', '𝐢')
        .replaceAll('j', '𝐣')
        .replaceAll('k', '𝐤')
        .replaceAll('l', '𝐥')
        .replaceAll('m', '𝐦')
        .replaceAll('n', '𝐧')
        .replaceAll('o', '𝐨')
        .replaceAll('p', '𝐩')
        .replaceAll('q', '𝐪')
        .replaceAll('r', '𝐫')
        .replaceAll('s', '𝐬')
        .replaceAll('t', '𝐭')
        .replaceAll('u', '𝐮')
        .replaceAll('v', '𝐯')
        .replaceAll('w', '𝐰')
        .replaceAll('x', '𝐱')
        .replaceAll('y', '𝐲')
        .replaceAll('z', '𝐳')
        .replaceAll('A', '𝐀')
        .replaceAll('B', '𝐁')
        .replaceAll('C', '𝐂')
        .replaceAll('D', '𝐃')
        .replaceAll('E', '𝐄')
        .replaceAll('F', '𝐅')
        .replaceAll('G', '𝐆')
        .replaceAll('H', '𝐇')
        .replaceAll('I', '𝐈')
        .replaceAll('J', '𝐉')
        .replaceAll('K', '𝐊')
        .replaceAll('L', '𝐋')
        .replaceAll('M', '𝐌')
        .replaceAll('N', '𝐍')
        .replaceAll('O', '𝐎')
        .replaceAll('P', '𝐏')
        .replaceAll('Q', '𝐐')
        .replaceAll('R', '𝐑')
        .replaceAll('S', '𝐒')
        .replaceAll('T', '𝐓')
        .replaceAll('U', '𝐔')
        .replaceAll('V', '𝐕')
        .replaceAll('W', '𝐖')
        .replaceAll('X', '𝐗')
        .replaceAll('Y', '𝐘')
        .replaceAll('Z', '𝐙');
return QueenFont  
        
      
  }

      //|⬡═══════════════════// 20 //══════════════════════|❝ Ⓒ𝙰𝙻𝙸𝙴𝙽 𝙰𝙻𝙵𝙰 𝙱𝙾𝚃 𝙱𝚈 𝚃𝙾𝚇𝙸𝙲 𝙰𝙻𝙸𝙴𝙽™ ❞|═══════════════════════════════════════════⬡|//	

  function QueenFont20(textz)  {  
     QueenFont = textz  
        .replaceAll('0', '𝟬')
        .replaceAll('1', '𝟭')
        .replaceAll('2', '𝟮')
        .replaceAll('3', '𝟯')
        .replaceAll('4', '𝟰')
        .replaceAll('5', '𝟱')
        .replaceAll('6', '𝟲')
        .replaceAll('7', '𝟳')
        .replaceAll('8', '𝟴')
        .replaceAll('9', '𝟵')
        .replaceAll('a', '𝗮')
        .replaceAll('b', '𝗯')
        .replaceAll('c', '𝗰')
        .replaceAll('d', '𝗱')
        .replaceAll('e', '𝗲')
        .replaceAll('f', '𝗳')
        .replaceAll('g', '𝗴')
        .replaceAll('h', '𝗵')
        .replaceAll('i', '𝗶')
        .replaceAll('j', '𝗷')
        .replaceAll('k', '𝗸')
        .replaceAll('l', '𝗹')
        .replaceAll('m', '𝗺')
        .replaceAll('n', '𝗻')
        .replaceAll('o', '𝗼')
        .replaceAll('p', '𝗽')
        .replaceAll('q', '𝗾')
        .replaceAll('r', '𝗿')
        .replaceAll('s', '𝘀')
        .replaceAll('t', '𝘁')
        .replaceAll('u', '𝘂')
        .replaceAll('v', '𝘃')
        .replaceAll('w', '𝘄')
        .replaceAll('x', '𝘅')
        .replaceAll('y', '𝘆')
        .replaceAll('z', '𝘇')
        .replaceAll('A', '𝗔')
        .replaceAll('B', '𝗕')
        .replaceAll('C', '𝗖')
        .replaceAll('D', '𝗗')
        .replaceAll('E', '𝗘')
        .replaceAll('F', '𝗙')
        .replaceAll('G', '𝗚')
        .replaceAll('H', '𝗛')
        .replaceAll('I', '𝗜')
        .replaceAll('J', '𝗝')
        .replaceAll('K', '𝗞')
        .replaceAll('L', '𝗟')
        .replaceAll('M', '𝗠')
        .replaceAll('N', '𝗡')
        .replaceAll('O', '𝗢')
        .replaceAll('P', '𝗣')
        .replaceAll('Q', '𝗤')
        .replaceAll('R', '𝗥')
        .replaceAll('S', '𝗦')
        .replaceAll('T', '𝗧')
        .replaceAll('U', '𝗨')
        .replaceAll('V', '𝗩')
        .replaceAll('W', '𝗪')
        .replaceAll('X', '𝗫')
        .replaceAll('Y', '𝗬')
        .replaceAll('Z', '𝗭');
return QueenFont  
        
      
  }

      //|⬡═══════════════════// 21 //══════════════════════|❝ Ⓒ𝙰𝙻𝙸𝙴𝙽 𝙰𝙻𝙵𝙰 𝙱𝙾𝚃 𝙱𝚈 𝚃𝙾𝚇𝙸𝙲 𝙰𝙻𝙸𝙴𝙽™ ❞|═══════════════════════════════════════════⬡|//	

  function QueenFont21(textz)  {  
     QueenFont = textz
        .replaceAll('0', '0')
        .replaceAll('1', '1')
        .replaceAll('2', '2')
        .replaceAll('3', '3')
        .replaceAll('4', '4')
        .replaceAll('5', '5')
        .replaceAll('6', '6')
        .replaceAll('7', '7')
        .replaceAll('8', '8')
        .replaceAll('9', '9')
        .replaceAll('a', '𝘢')
        .replaceAll('b', '𝘣')
        .replaceAll('c', '𝘤')
        .replaceAll('d', '𝘥')
        .replaceAll('e', '𝘦')
        .replaceAll('f', '𝘧')
        .replaceAll('g', '𝘨')
        .replaceAll('h', '𝘩')
        .replaceAll('i', '𝘪')
        .replaceAll('j', '𝘫')
        .replaceAll('k', '𝘬')
        .replaceAll('l', '𝘭')
        .replaceAll('m', '𝘮')
        .replaceAll('n', '𝘯')
        .replaceAll('o', '𝘰')
        .replaceAll('p', '𝘱')
        .replaceAll('q', '𝘲')
        .replaceAll('r', '𝘳')
        .replaceAll('s', '𝘴')
        .replaceAll('t', '𝘵')
        .replaceAll('u', '𝘶')
        .replaceAll('v', '𝘷')
        .replaceAll('w', '𝘸')
        .replaceAll('x', '𝘹')
        .replaceAll('y', '𝘺')
        .replaceAll('z', '𝘻')
        .replaceAll('A', '𝘈')
        .replaceAll('B', '𝘉')
        .replaceAll('C', '𝘊')
        .replaceAll('D', '𝘋')
        .replaceAll('E', '𝘌')
        .replaceAll('F', '𝘍')
        .replaceAll('G', '𝘎')
        .replaceAll('H', '𝘏')
        .replaceAll('I', '𝘐')
        .replaceAll('J', '𝘑')
        .replaceAll('K', '𝘒')
        .replaceAll('L', '𝘓')
        .replaceAll('M', '𝘔')
        .replaceAll('N', '𝘕')
        .replaceAll('O', '𝘖')
        .replaceAll('P', '𝘗')
        .replaceAll('Q', '𝘘')
        .replaceAll('R', '𝘙')
        .replaceAll('S', '𝘚')
        .replaceAll('T', '𝘛')
        .replaceAll('U', '𝘜')
        .replaceAll('V', '𝘝')
        .replaceAll('W', '𝘞')
        .replaceAll('X', '𝘟')
        .replaceAll('Y', '𝘠')
        .replaceAll('Z', '𝘡');
return QueenFont  
        
      
  }

      //|⬡═══════════════════// 22 //══════════════════════|❝ Ⓒ𝙰𝙻𝙸𝙴𝙽 𝙰𝙻𝙵𝙰 𝙱𝙾𝚃 𝙱𝚈 𝚃𝙾𝚇𝙸𝙲 𝙰𝙻𝙸𝙴𝙽™ ❞|═══════════════════════════════════════════⬡|//	

  function QueenFont22(textz)  {  
     QueenFont = textz
        .replaceAll('0', '0')
        .replaceAll('1', '1')
        .replaceAll('2', '2')
        .replaceAll('3', '3')
        .replaceAll('4', '4')
        .replaceAll('5', '5')
        .replaceAll('6', '6')
        .replaceAll('7', '7')
        .replaceAll('8', '8')
        .replaceAll('9', '9')
        .replaceAll('a', 'α')
        .replaceAll('b', 'Ⴆ')
        .replaceAll('c', 'ƈ')
        .replaceAll('d', 'ԃ')
        .replaceAll('e', 'ҽ')
        .replaceAll('f', 'ϝ')
        .replaceAll('g', 'ɠ')
        .replaceAll('h', 'ԋ')
        .replaceAll('i', 'ι')
        .replaceAll('j', 'ʝ')
        .replaceAll('k', 'ƙ')
        .replaceAll('l', 'ʅ')
        .replaceAll('m', 'ɱ')
        .replaceAll('n', 'ɳ')
        .replaceAll('o', 'σ')
        .replaceAll('p', 'ρ')
        .replaceAll('q', 'ϙ')
        .replaceAll('r', 'ɾ')
        .replaceAll('s', 'ʂ')
        .replaceAll('t', 'ƚ')
        .replaceAll('u', 'υ')
        .replaceAll('v', 'ʋ')
        .replaceAll('w', 'ɯ')
        .replaceAll('x', 'x')
        .replaceAll('y', 'ყ')
        .replaceAll('z', 'ȥ')
        .replaceAll('A', 'A')
        .replaceAll('B', 'B')
        .replaceAll('C', 'C')
        .replaceAll('D', 'D')
        .replaceAll('E', 'E')
        .replaceAll('F', 'F')
        .replaceAll('G', 'G')
        .replaceAll('H', 'H')
        .replaceAll('I', 'I')
        .replaceAll('J', 'J')
        .replaceAll('K', 'K')
        .replaceAll('L', 'L')
        .replaceAll('M', 'M')
        .replaceAll('N', 'N')
        .replaceAll('O', 'O')
        .replaceAll('P', 'P')
        .replaceAll('Q', 'Q')
        .replaceAll('R', 'R')
        .replaceAll('S', 'S')
        .replaceAll('T', 'T')
        .replaceAll('U', 'U')
        .replaceAll('V', 'V')
        .replaceAll('W', 'W')
        .replaceAll('X', 'X')
        .replaceAll('Y', 'Y')
        .replaceAll('Z', 'Z');
return QueenFont  
        
      
  }

      //|⬡═══════════════════// 23 //══════════════════════|❝ Ⓒ𝙰𝙻𝙸𝙴𝙽 𝙰𝙻𝙵𝙰 𝙱𝙾𝚃 𝙱𝚈 𝚃𝙾𝚇𝙸𝙲 𝙰𝙻𝙸𝙴𝙽™ ❞|═══════════════════════════════════════════⬡|//	

  function QueenFont23(textz)  {  
     QueenFont = textz
        .replaceAll('0', '0')
        .replaceAll('1', '1')
        .replaceAll('2', '2')
        .replaceAll('3', '3')
        .replaceAll('4', '4')
        .replaceAll('5', '5')
        .replaceAll('6', '6')
        .replaceAll('7', '7')
        .replaceAll('8', '8')
        .replaceAll('9', '9')
        .replaceAll('a', '₳')
        .replaceAll('b', '฿')
        .replaceAll('c', '₵')
        .replaceAll('d', 'Đ')
        .replaceAll('e', 'Ɇ')
        .replaceAll('f', '₣')
        .replaceAll('g', '₲')
        .replaceAll('h', 'Ⱨ')
        .replaceAll('i', 'ł')
        .replaceAll('j', 'J')
        .replaceAll('k', '₭')
        .replaceAll('l', 'Ⱡ')
        .replaceAll('m', '₥')
        .replaceAll('n', '₦')
        .replaceAll('o', 'Ø')
        .replaceAll('p', '₱')
        .replaceAll('q', 'Q')
        .replaceAll('r', 'Ɽ')
        .replaceAll('s', '₴')
        .replaceAll('t', '₮')
        .replaceAll('u', 'Ʉ')
        .replaceAll('v', 'V')
        .replaceAll('w', '₩')
        .replaceAll('x', 'Ӿ')
        .replaceAll('y', 'Ɏ')
        .replaceAll('z', 'Ⱬ')
        .replaceAll('A', '₳')
        .replaceAll('B', '฿')
        .replaceAll('C', '₵')
        .replaceAll('D', 'Đ')
        .replaceAll('E', 'Ɇ')
        .replaceAll('F', '₣')
        .replaceAll('G', '₲')
        .replaceAll('H', 'Ⱨ')
        .replaceAll('I', 'ł')
        .replaceAll('J', 'J')
        .replaceAll('K', '₭')
        .replaceAll('L', 'Ⱡ')
        .replaceAll('M', '₥')
        .replaceAll('N', '₦')
        .replaceAll('O', 'Ø')
        .replaceAll('P', '₱')
        .replaceAll('Q', 'Q')
        .replaceAll('R', 'Ɽ')
        .replaceAll('S', '₴')
        .replaceAll('T', '₮')
        .replaceAll('U', 'Ʉ')
        .replaceAll('V', 'V')
        .replaceAll('W', '₩')
        .replaceAll('X', 'Ӿ')
        .replaceAll('Y', 'Ɏ')
        .replaceAll('Z', 'Ⱬ');
return QueenFont  
        
      
  }

      //|⬡═══════════════════// 24 //══════════════════════|❝ Ⓒ𝙰𝙻𝙸𝙴𝙽 𝙰𝙻𝙵𝙰 𝙱𝙾𝚃 𝙱𝚈 𝚃𝙾𝚇𝙸𝙲 𝙰𝙻𝙸𝙴𝙽™ ❞|═══════════════════════════════════════════⬡|//	

  function QueenFont24(textz)  {  
     QueenFont = textz
        .replaceAll('0', '0')
        .replaceAll('1', '1')
        .replaceAll('2', '2')
        .replaceAll('3', '3')
        .replaceAll('4', '4')
        .replaceAll('5', '5')
        .replaceAll('6', '6')
        .replaceAll('7', '7')
        .replaceAll('8', '8')
        .replaceAll('9', '9')
        .replaceAll('a', 'å')
        .replaceAll('b', 'ß')
        .replaceAll('c', '¢')
        .replaceAll('d', 'Ð')
        .replaceAll('e', 'ê')
        .replaceAll('f', '£')
        .replaceAll('g', 'g')
        .replaceAll('h', 'h')
        .replaceAll('i', 'ï')
        .replaceAll('j', 'j')
        .replaceAll('k', 'k')
        .replaceAll('l', 'l')
        .replaceAll('m', 'm')
        .replaceAll('n', 'ñ')
        .replaceAll('o', 'ð')
        .replaceAll('p', 'þ')
        .replaceAll('q', 'q')
        .replaceAll('r', 'r')
        .replaceAll('s', '§')
        .replaceAll('t', '†')
        .replaceAll('u', 'µ')
        .replaceAll('v', 'v')
        .replaceAll('w', 'w')
        .replaceAll('x', 'x')
        .replaceAll('y', '¥')
        .replaceAll('z', 'z')
        .replaceAll('A', 'Ä')
        .replaceAll('B', 'ß')
        .replaceAll('C', 'Ç')
        .replaceAll('D', 'Ð')
        .replaceAll('E', 'È')
        .replaceAll('F', '£')
        .replaceAll('G', 'G')
        .replaceAll('H', 'H')
        .replaceAll('I', 'Ì')
        .replaceAll('J', 'J')
        .replaceAll('K', 'K')
        .replaceAll('L', 'L')
        .replaceAll('M', 'M')
        .replaceAll('N', 'ñ')
        .replaceAll('O', 'Ö')
        .replaceAll('P', 'þ')
        .replaceAll('Q', 'Q')
        .replaceAll('R', 'R')
        .replaceAll('S', '§')
        .replaceAll('T', '†')
        .replaceAll('U', 'Ú')
        .replaceAll('V', 'V')
        .replaceAll('W', 'W')
        .replaceAll('X', '×')
        .replaceAll('Y', '¥')
        .replaceAll('Z', 'Z');
return QueenFont  
        
      
  }

      //|⬡═══════════════════// 25 //══════════════════════|❝ Ⓒ𝙰𝙻𝙸𝙴𝙽 𝙰𝙻𝙵𝙰 𝙱𝙾𝚃 𝙱𝚈 𝚃𝙾𝚇𝙸𝙲 𝙰𝙻𝙸𝙴𝙽™ ❞|═══════════════════════════════════════════⬡|//	

  function QueenFont25(textz)  {  
     QueenFont = textz
        .replaceAll('0', '0')
        .replaceAll('1', '1')
        .replaceAll('2', '2')
        .replaceAll('3', '3')
        .replaceAll('4', '4')
        .replaceAll('5', '5')
        .replaceAll('6', '6')
        .replaceAll('7', '7')
        .replaceAll('8', '8')
        .replaceAll('9', '9')
        .replaceAll('a', 'α')
        .replaceAll('b', 'в')
        .replaceAll('c', '¢')
        .replaceAll('d', '∂')
        .replaceAll('e', 'є')
        .replaceAll('f', 'ƒ')
        .replaceAll('g', 'g')
        .replaceAll('h', 'н')
        .replaceAll('i', 'ι')
        .replaceAll('j', 'נ')
        .replaceAll('k', 'к')
        .replaceAll('l', 'ℓ')
        .replaceAll('m', 'м')
        .replaceAll('n', 'η')
        .replaceAll('o', 'σ')
        .replaceAll('p', 'ρ')
        .replaceAll('q', 'q')
        .replaceAll('r', 'я')
        .replaceAll('s', 'ѕ')
        .replaceAll('t', 'т')
        .replaceAll('u', 'υ')
        .replaceAll('v', 'ν')
        .replaceAll('w', 'ω')
        .replaceAll('x', 'χ')
        .replaceAll('y', 'у')
        .replaceAll('z', 'z')
        .replaceAll('A', 'α')
        .replaceAll('B', 'в')
        .replaceAll('C', '¢')
        .replaceAll('D', '∂')
        .replaceAll('E', 'є')
        .replaceAll('F', 'ƒ')
        .replaceAll('G', 'g')
        .replaceAll('H', 'н')
        .replaceAll('I', 'ι')
        .replaceAll('J', 'נ')
        .replaceAll('K', 'к')
        .replaceAll('L', 'ℓ')
        .replaceAll('M', 'м')
        .replaceAll('N', 'η')
        .replaceAll('O', 'σ')
        .replaceAll('P', 'ρ')
        .replaceAll('Q', 'q')
        .replaceAll('R', 'я')
        .replaceAll('S', 'ѕ')
        .replaceAll('T', 'т')
        .replaceAll('U', 'υ')
        .replaceAll('V', 'ν')
        .replaceAll('W', 'ω')
        .replaceAll('X', 'χ')
        .replaceAll('Y', 'у')
        .replaceAll('Z', 'z');
return QueenFont  
        
      
  }

      //|⬡═══════════════════// 26 //══════════════════════|❝ Ⓒ𝙰𝙻𝙸𝙴𝙽 𝙰𝙻𝙵𝙰 𝙱𝙾𝚃 𝙱𝚈 𝚃𝙾𝚇𝙸𝙲 𝙰𝙻𝙸𝙴𝙽™ ❞|═══════════════════════════════════════════⬡|//	

  function QueenFont26(textz)  {  
     QueenFont = textz
        .replaceAll('0', '⊘')
        .replaceAll('1', '𝟙')
        .replaceAll('2', 'ϩ')
        .replaceAll('3', 'Ӡ')
        .replaceAll('4', '५')
        .replaceAll('5', 'Ƽ')
        .replaceAll('6', 'Ϭ')
        .replaceAll('7', '7')
        .replaceAll('8', '𝟠')
        .replaceAll('9', '९')
        .replaceAll('a', 'ą')
        .replaceAll('b', 'ҍ')
        .replaceAll('c', 'ç')
        .replaceAll('d', 'ժ')
        .replaceAll('e', 'ҽ')
        .replaceAll('f', 'ƒ')
        .replaceAll('g', 'ց')
        .replaceAll('h', 'հ')
        .replaceAll('i', 'ì')
        .replaceAll('j', 'ʝ')
        .replaceAll('k', 'ҟ')
        .replaceAll('l', 'Ӏ')
        .replaceAll('m', 'ʍ')
        .replaceAll('n', 'ղ')
        .replaceAll('o', 'օ')
        .replaceAll('p', 'ք')
        .replaceAll('q', 'զ')
        .replaceAll('r', 'ɾ')
        .replaceAll('s', 'ʂ')
        .replaceAll('t', 'է')
        .replaceAll('u', 'մ')
        .replaceAll('v', 'ѵ')
        .replaceAll('w', 'ա')
        .replaceAll('x', '×')
        .replaceAll('y', 'վ')
        .replaceAll('z', 'Հ')
        .replaceAll('A', 'Ⱥ')
        .replaceAll('B', 'β')
        .replaceAll('C', '↻')
        .replaceAll('D', 'Ꭰ')
        .replaceAll('E', 'Ɛ')
        .replaceAll('F', 'Ƒ')
        .replaceAll('G', 'Ɠ')
        .replaceAll('H', 'Ƕ')
        .replaceAll('I', 'į')
        .replaceAll('J', 'ل')
        .replaceAll('K', 'Ҡ')
        .replaceAll('L', 'Ꝉ')
        .replaceAll('M', 'Ɱ')
        .replaceAll('N', 'ហ')
        .replaceAll('O', 'ට')
        .replaceAll('P', 'φ')
        .replaceAll('Q', 'Ҩ')
        .replaceAll('R', 'འ')
        .replaceAll('S', 'Ϛ')
        .replaceAll('T', 'Ͳ')
        .replaceAll('U', 'Ա')
        .replaceAll('V', 'Ỽ')
        .replaceAll('W', 'చ')
        .replaceAll('X', 'ჯ')
        .replaceAll('Y', 'Ӌ')
        .replaceAll('Z', 'ɀ');
return QueenFont  
        
      
  }

      //|⬡═══════════════════// 27 //══════════════════════|❝ Ⓒ𝙰𝙻𝙸𝙴𝙽 𝙰𝙻𝙵𝙰 𝙱𝙾𝚃 𝙱𝚈 𝚃𝙾𝚇𝙸𝙲 𝙰𝙻𝙸𝙴𝙽™ ❞|═══════════════════════════════════════════⬡|//	

  function QueenFont27(textz)  {  
     QueenFont = textz
        .replaceAll('0', '0')
        .replaceAll('1', '1')
        .replaceAll('2', '2')
        .replaceAll('3', '3')
        .replaceAll('4', '4')
        .replaceAll('5', '5')
        .replaceAll('6', '6')
        .replaceAll('7', '7')
        .replaceAll('8', '8')
        .replaceAll('9', '9')
        .replaceAll('a', 'Λ')
        .replaceAll('b', 'B')
        .replaceAll('c', 'ᄃ')
        .replaceAll('d', 'D')
        .replaceAll('e', 'Σ')
        .replaceAll('f', 'F')
        .replaceAll('g', 'G')
        .replaceAll('h', 'Ή')
        .replaceAll('i', 'I')
        .replaceAll('j', 'J')
        .replaceAll('k', 'K')
        .replaceAll('l', 'ᄂ')
        .replaceAll('m', 'M')
        .replaceAll('n', 'П')
        .replaceAll('o', 'Ө')
        .replaceAll('p', 'P')
        .replaceAll('q', 'Q')
        .replaceAll('r', 'Я')
        .replaceAll('s', 'Ƨ')
        .replaceAll('t', 'Ƭ')
        .replaceAll('u', 'Ц')
        .replaceAll('v', 'V')
        .replaceAll('w', 'Щ')
        .replaceAll('x', 'X')
        .replaceAll('y', 'Y')
        .replaceAll('z', 'Z')
        .replaceAll('A', 'Λ')
        .replaceAll('B', 'B')
        .replaceAll('C', 'ᄃ')
        .replaceAll('D', 'D')
        .replaceAll('E', 'Σ')
        .replaceAll('F', 'F')
        .replaceAll('G', 'G')
        .replaceAll('H', 'Ή')
        .replaceAll('I', 'I')
        .replaceAll('J', 'J')
        .replaceAll('K', 'K')
        .replaceAll('L', 'ᄂ')
        .replaceAll('M', 'M')
        .replaceAll('N', 'П')
        .replaceAll('O', 'Ө')
        .replaceAll('P', 'P')
        .replaceAll('Q', 'Q')
        .replaceAll('R', 'Я')
        .replaceAll('S', 'Ƨ')
        .replaceAll('T', 'Ƭ')
        .replaceAll('U', 'Ц')
        .replaceAll('V', 'V')
        .replaceAll('W', 'Щ')
        .replaceAll('X', 'X')
        .replaceAll('Y', 'Y')
        .replaceAll('Z', 'Z');
return QueenFont  
        
      
  }

      //|⬡═══════════════════// 28 //══════════════════════|❝ Ⓒ𝙰𝙻𝙸𝙴𝙽 𝙰𝙻𝙵𝙰 𝙱𝙾𝚃 𝙱𝚈 𝚃𝙾𝚇𝙸𝙲 𝙰𝙻𝙸𝙴𝙽™ ❞|═══════════════════════════════════════════⬡|//	

  function QueenFont28(textz)  {  
     QueenFont = textz
        .replaceAll('0', '₀')
        .replaceAll('1', '₁')
        .replaceAll('2', '₂')
        .replaceAll('3', '₃')
        .replaceAll('4', '₄')
        .replaceAll('5', '₅')
        .replaceAll('6', '₆')
        .replaceAll('7', '₇')
        .replaceAll('8', '₈')
        .replaceAll('9', '₉')
        .replaceAll('a', 'ₐ')
        .replaceAll('b', 'b')
        .replaceAll('c', 'c')
        .replaceAll('d', 'd')
        .replaceAll('e', 'ₑ')
        .replaceAll('f', 'f')
        .replaceAll('g', 'g')
        .replaceAll('h', 'ₕ')
        .replaceAll('i', 'ᵢ')
        .replaceAll('j', 'ⱼ')
        .replaceAll('k', 'ₖ')
        .replaceAll('l', 'ₗ')
        .replaceAll('m', 'ₘ')
        .replaceAll('n', 'ₙ')
        .replaceAll('o', 'ₒ')
        .replaceAll('p', 'ₚ')
        .replaceAll('q', 'q')
        .replaceAll('r', 'ᵣ')
        .replaceAll('s', 'ₛ')
        .replaceAll('t', 'ₜ')
        .replaceAll('u', 'ᵤ')
        .replaceAll('v', 'ᵥ')
        .replaceAll('w', 'w')
        .replaceAll('x', 'ₓ')
        .replaceAll('y', 'y')
        .replaceAll('z', 'z')
        .replaceAll('A', 'ₐ')
        .replaceAll('B', 'B')
        .replaceAll('C', 'C')
        .replaceAll('D', 'D')
        .replaceAll('E', 'ₑ')
        .replaceAll('F', 'F')
        .replaceAll('G', 'G')
        .replaceAll('H', 'ₕ')
        .replaceAll('I', 'ᵢ')
        .replaceAll('J', 'ⱼ')
        .replaceAll('K', 'ₖ')
        .replaceAll('L', 'ₗ')
        .replaceAll('M', 'ₘ')
        .replaceAll('N', 'ₙ')
        .replaceAll('O', 'ₒ')
        .replaceAll('P', 'ₚ')
        .replaceAll('Q', 'Q')
        .replaceAll('R', 'ᵣ')
        .replaceAll('S', 'ₛ')
        .replaceAll('T', 'ₜ')
        .replaceAll('U', 'ᵤ')
        .replaceAll('V', 'ᵥ')
        .replaceAll('W', 'W')
        .replaceAll('X', 'ₓ')
        .replaceAll('Y', 'Y')
        .replaceAll('Z', 'Z')
        .replaceAll('+', '₊')
        .replaceAll('-', '₋')
        .replaceAll('=', '₌')
        .replaceAll('(', '₍')
        .replaceAll(')', '₎');
return QueenFont  
        
      
  }

      //|⬡═══════════════════// 29 //══════════════════════|❝ Ⓒ𝙰𝙻𝙸𝙴𝙽 𝙰𝙻𝙵𝙰 𝙱𝙾𝚃 𝙱𝚈 𝚃𝙾𝚇𝙸𝙲 𝙰𝙻𝙸𝙴𝙽™ ❞|═══════════════════════════════════════════⬡|//	

  function QueenFont29(textz)  {  
     QueenFont = textz
        .replaceAll('0', '⁰')
        .replaceAll('1', '¹')
        .replaceAll('2', '²')
        .replaceAll('3', '³')
        .replaceAll('4', '⁴')
        .replaceAll('5', '⁵')
        .replaceAll('6', '⁶')
        .replaceAll('7', '⁷')
        .replaceAll('8', '⁸')
        .replaceAll('9', '⁹')
        .replaceAll('a', 'ᵃ')
        .replaceAll('b', 'ᵇ')
        .replaceAll('c', 'ᶜ')
        .replaceAll('d', 'ᵈ')
        .replaceAll('e', 'ᵉ')
        .replaceAll('f', 'ᶠ')
        .replaceAll('g', 'ᵍ')
        .replaceAll('h', 'ʰ')
        .replaceAll('i', 'ⁱ')
        .replaceAll('j', 'ʲ')
        .replaceAll('k', 'ᵏ')
        .replaceAll('l', 'ˡ')
        .replaceAll('m', 'ᵐ')
        .replaceAll('n', 'ⁿ')
        .replaceAll('o', 'ᵒ')
        .replaceAll('p', 'ᵖ')
        .replaceAll('q', 'q')
        .replaceAll('r', 'ʳ')
        .replaceAll('s', 'ˢ')
        .replaceAll('t', 'ᵗ')
        .replaceAll('u', 'ᵘ')
        .replaceAll('v', 'ᵛ')
        .replaceAll('w', 'ʷ')
        .replaceAll('x', 'ˣ')
        .replaceAll('y', 'ʸ')
        .replaceAll('z', 'ᶻ')
        .replaceAll('A', 'ᴬ')
        .replaceAll('B', 'ᴮ')
        .replaceAll('C', 'ᶜ')
        .replaceAll('D', 'ᴰ')
        .replaceAll('E', 'ᴱ')
        .replaceAll('F', 'ᶠ')
        .replaceAll('G', 'ᴳ')
        .replaceAll('H', 'ᴴ')
        .replaceAll('I', 'ᴵ')
        .replaceAll('J', 'ᴶ')
        .replaceAll('K', 'ᴷ')
        .replaceAll('L', 'ᴸ')
        .replaceAll('M', 'ᴹ')
        .replaceAll('N', 'ᴺ')
        .replaceAll('O', 'ᴼ')
        .replaceAll('P', 'ᴾ')
        .replaceAll('Q', 'Q')
        .replaceAll('R', 'ᴿ')
        .replaceAll('S', 'ˢ')
        .replaceAll('T', 'ᵀ')
        .replaceAll('U', 'ᵁ')
        .replaceAll('V', 'ⱽ')
        .replaceAll('W', 'ᵂ')
        .replaceAll('X', 'ˣ')
        .replaceAll('Y', 'ʸ')
        .replaceAll('Z', 'ᶻ')
        .replaceAll('+', '⁺')
        .replaceAll('-', '⁻')
        .replaceAll('=', '⁼')
        .replaceAll('(', '⁽')
        .replaceAll(')', '⁾');
return QueenFont  
        
      
  }

      //|⬡═══════════════════// 30 //══════════════════════|❝ Ⓒ𝙰𝙻𝙸𝙴𝙽 𝙰𝙻𝙵𝙰 𝙱𝙾𝚃 𝙱𝚈 𝚃𝙾𝚇𝙸𝙲 𝙰𝙻𝙸𝙴𝙽™ ❞|═══════════════════════════════════════════⬡|//	

  function QueenFont30(textz)  {  
     QueenFont = textz
        .replaceAll('0', '0')
        .replaceAll('1', '1')
        .replaceAll('2', '2')
        .replaceAll('3', '3')
        .replaceAll('4', '4')
        .replaceAll('5', '5')
        .replaceAll('6', '6')
        .replaceAll('7', '7')
        .replaceAll('8', '8')
        .replaceAll('9', '9')
        .replaceAll('a', 'ค')
        .replaceAll('b', '๒')
        .replaceAll('c', 'ς')
        .replaceAll('d', '๔')
        .replaceAll('e', 'є')
        .replaceAll('f', 'Ŧ')
        .replaceAll('g', 'ﻮ')
        .replaceAll('h', 'ђ')
        .replaceAll('i', 'เ')
        .replaceAll('j', 'ן')
        .replaceAll('k', 'к')
        .replaceAll('l', 'ɭ')
        .replaceAll('m', '๓')
        .replaceAll('n', 'ภ')
        .replaceAll('o', '๏')
        .replaceAll('p', 'ק')
        .replaceAll('q', 'ợ')
        .replaceAll('r', 'г')
        .replaceAll('s', 'ร')
        .replaceAll('t', 'Շ')
        .replaceAll('u', 'ย')
        .replaceAll('v', 'ש')
        .replaceAll('w', 'ฬ')
        .replaceAll('x', 'א')
        .replaceAll('y', 'ץ')
        .replaceAll('z', 'չ')
        .replaceAll('A', 'ค')
        .replaceAll('B', '๒')
        .replaceAll('C', 'ς')
        .replaceAll('D', '๔')
        .replaceAll('E', 'є')
        .replaceAll('F', 'Ŧ')
        .replaceAll('G', 'ﻮ')
        .replaceAll('H', 'ђ')
        .replaceAll('I', 'เ')
        .replaceAll('J', 'ן')
        .replaceAll('K', 'к')
        .replaceAll('L', 'ɭ')
        .replaceAll('M', '๓')
        .replaceAll('N', 'ภ')
        .replaceAll('O', '๏')
        .replaceAll('P', 'ק')
        .replaceAll('Q', 'ợ')
        .replaceAll('R', 'г')
        .replaceAll('S', 'ร')
        .replaceAll('T', 'Շ')
        .replaceAll('U', 'ย')
        .replaceAll('V', 'ש')
        .replaceAll('W', 'ฬ')
        .replaceAll('X', 'א')
        .replaceAll('Y', 'ץ')
        .replaceAll('Z', 'չ');
return QueenFont  
        
      
  }

      //|⬡═══════════════════// 31 //══════════════════════|❝ Ⓒ𝙰𝙻𝙸𝙴𝙽 𝙰𝙻𝙵𝙰 𝙱𝙾𝚃 𝙱𝚈 𝚃𝙾𝚇𝙸𝙲 𝙰𝙻𝙸𝙴𝙽™ ❞|═══════════════════════════════════════════⬡|//	

  function QueenFont31(textz)  {  
     QueenFont = textz
        .replaceAll('0', '𝟘')
        .replaceAll('1', '𝟙')
        .replaceAll('2', '𝟚')
        .replaceAll('3', '𝟛')
        .replaceAll('4', '𝟜')
        .replaceAll('5', '𝟝')
        .replaceAll('6', '𝟞')
        .replaceAll('7', '𝟟')
        .replaceAll('8', '𝟠')
        .replaceAll('9', '𝟡')
        .replaceAll('a', '𝕒')
        .replaceAll('b', '𝕓')
        .replaceAll('c', '𝕔')
        .replaceAll('d', '𝕕')
        .replaceAll('e', '𝕖')
        .replaceAll('f', '𝕗')
        .replaceAll('g', '𝕘')
        .replaceAll('h', '𝕙')
        .replaceAll('i', '𝕚')
        .replaceAll('j', '𝕛')
        .replaceAll('k', '𝕜')
        .replaceAll('l', '𝕝')
        .replaceAll('m', '𝕞')
        .replaceAll('n', '𝕟')
        .replaceAll('o', '𝕠')
        .replaceAll('p', '𝕡')
        .replaceAll('q', '𝕢')
        .replaceAll('r', '𝕣')
        .replaceAll('s', '𝕤')
        .replaceAll('t', '𝕥')
        .replaceAll('u', '𝕦')
        .replaceAll('v', '𝕧')
        .replaceAll('w', '𝕨')
        .replaceAll('x', '𝕩')
        .replaceAll('y', '𝕪')
        .replaceAll('z', '𝕫')
        .replaceAll('A', '𝔸')
        .replaceAll('B', '𝔹')
        .replaceAll('C', 'ℂ')
        .replaceAll('D', '𝔻')
        .replaceAll('E', '𝔼')
        .replaceAll('F', '𝔽')
        .replaceAll('G', '𝔾')
        .replaceAll('H', 'ℍ')
        .replaceAll('I', '𝕀')
        .replaceAll('J', '𝕁')
        .replaceAll('K', '𝕂')
        .replaceAll('L', '𝕃')
        .replaceAll('M', '𝕄')
        .replaceAll('N', 'ℕ')
        .replaceAll('O', '𝕆')
        .replaceAll('P', 'ℙ')
        .replaceAll('Q', 'ℚ')
        .replaceAll('R', 'ℝ')
        .replaceAll('S', '𝕊')
        .replaceAll('T', '𝕋')
        .replaceAll('U', '𝕌')
        .replaceAll('V', '𝕍')
        .replaceAll('W', '𝕎')
        .replaceAll('X', '𝕏')
        .replaceAll('Y', '𝕐')
        .replaceAll('Z', 'ℤ');
return QueenFont  
        
      
  }

      //|⬡═══════════════════// 32 //══════════════════════|❝ Ⓒ𝙰𝙻𝙸𝙴𝙽 𝙰𝙻𝙵𝙰 𝙱𝙾𝚃 𝙱𝚈 𝚃𝙾𝚇𝙸𝙲 𝙰𝙻𝙸𝙴𝙽™ ❞|═══════════════════════════════════════════⬡|//	

  function QueenFont32(textz)  {  
     QueenFont = textz
        .replaceAll('0', '0')
        .replaceAll('1', '1')
        .replaceAll('2', '2')
        .replaceAll('3', '3')
        .replaceAll('4', '4')
        .replaceAll('5', '5')
        .replaceAll('6', '6')
        .replaceAll('7', '7')
        .replaceAll('8', '8')
        .replaceAll('9', '9')
        .replaceAll('a', '𝖆')
        .replaceAll('b', '𝖇')
        .replaceAll('c', '𝖈')
        .replaceAll('d', '𝖉')
        .replaceAll('e', '𝖊')
        .replaceAll('f', '𝖋')
        .replaceAll('g', '𝖌')
        .replaceAll('h', '𝖍')
        .replaceAll('i', '𝖎')
        .replaceAll('j', '𝖏')
        .replaceAll('k', '𝖐')
        .replaceAll('l', '𝖑')
        .replaceAll('m', '𝖒')
        .replaceAll('n', '𝖓')
        .replaceAll('o', '𝖔')
        .replaceAll('p', '𝖕')
        .replaceAll('q', '𝖖')
        .replaceAll('r', '𝖗')
        .replaceAll('s', '𝖘')
        .replaceAll('t', '𝖙')
        .replaceAll('u', '𝖚')
        .replaceAll('v', '𝖛')
        .replaceAll('w', '𝖜')
        .replaceAll('x', '𝖝')
        .replaceAll('y', '𝖞')
        .replaceAll('z', '𝖟')
        .replaceAll('A', '𝕬')
        .replaceAll('B', '𝕭')
        .replaceAll('C', '𝕮')
        .replaceAll('D', '𝕯')
        .replaceAll('E', '𝕰')
        .replaceAll('F', '𝕱')
        .replaceAll('G', '𝕲')
        .replaceAll('H', '𝕳')
        .replaceAll('I', '𝕴')
        .replaceAll('J', '𝕵')
        .replaceAll('K', '𝕶')
        .replaceAll('L', '𝕷')
        .replaceAll('M', '𝕸')
        .replaceAll('N', '𝕹')
        .replaceAll('O', '𝕺')
        .replaceAll('P', '𝕻')
        .replaceAll('Q', '𝕼')
        .replaceAll('R', '𝕽')
        .replaceAll('S', '𝕾')
        .replaceAll('T', '𝕿')
        .replaceAll('U', '𝖀')
        .replaceAll('V', '𝖁')
        .replaceAll('W', '𝖂')
        .replaceAll('X', '𝖃')
        .replaceAll('Y', '𝖄')
        .replaceAll('Z', '𝖅');
return QueenFont  
        
      
  }

  function QueenFont33(textz)  {  
     QueenFont = textz
        .replaceAll('q', '🆀')
        .replaceAll('w', '🆆')
        .replaceAll('e', '🅴')
        .replaceAll('r', '🆁')
        .replaceAll('t', '🆃')
        .replaceAll('y', '🆈')
        .replaceAll('u', '🆄')
        .replaceAll('i', '🅸')
        .replaceAll('o', '🅾')
        .replaceAll('p', '🅿')
        .replaceAll('a', '🅰')
        .replaceAll('s', '🆂')
        .replaceAll('d', '🅳')
        .replaceAll('f', '🅵')
        .replaceAll('g', '🅶')
        .replaceAll('h', '🅷')
        .replaceAll('j', '🅹')
        .replaceAll('k', '🅺')
        .replaceAll('l', '🅻')
        .replaceAll('z', '🆉')
        .replaceAll('x', '🆇')
        .replaceAll('c', '🅲')
        .replaceAll('v', '🆅')
        .replaceAll('b', '🅱')
        .replaceAll('n', '🅽')
        .replaceAll('m', '🅼');
return QueenFont  
        
      
  }

      //|⬡═══════════════════// 34 //══════════════════════|❝ Ⓒ𝙰𝙻𝙸𝙴𝙽 𝙰𝙻𝙵𝙰 𝙱𝙾𝚃 𝙱𝚈 𝚃𝙾𝚇𝙸𝙲 𝙰𝙻𝙸𝙴𝙽™ ❞|═══════════════════════════════════════════⬡|//	

  function QueenFont34(textz)  {  
     QueenFont = textz
        .replaceAll('0', '0')
        .replaceAll('1', '1')
        .replaceAll('2', '2')
        .replaceAll('3', '3')
        .replaceAll('4', '4')
        .replaceAll('5', '5')
        .replaceAll('6', '6')
        .replaceAll('7', '7')
        .replaceAll('8', '8')
        .replaceAll('9', '9')
        .replaceAll('a', '𝓪')
        .replaceAll('b', '𝓫')
        .replaceAll('c', '𝓬')
        .replaceAll('d', '𝓭')
        .replaceAll('e', '𝓮')
        .replaceAll('f', '𝓯')
        .replaceAll('g', '𝓰')
        .replaceAll('h', '𝓱')
        .replaceAll('i', '𝓲')
        .replaceAll('j', '𝓳')
        .replaceAll('k', '𝓴')
        .replaceAll('l', '𝓵')
        .replaceAll('m', '𝓶')
        .replaceAll('n', '𝓷')
        .replaceAll('o', '𝓸')
        .replaceAll('p', '𝓹')
        .replaceAll('q', '𝓺')
        .replaceAll('r', '𝓻')
        .replaceAll('s', '𝓼')
        .replaceAll('t', '𝓽')
        .replaceAll('u', '𝓾')
        .replaceAll('v', '𝓿')
        .replaceAll('w', '𝔀')
        .replaceAll('x', '𝔁')
        .replaceAll('y', '𝔂')
        .replaceAll('z', '𝔃')
        .replaceAll('A', '𝓐')
        .replaceAll('B', '𝓑')
        .replaceAll('C', '𝓒')
        .replaceAll('D', '𝓓')
        .replaceAll('E', '𝓔')
        .replaceAll('F', '𝓕')
        .replaceAll('G', '𝓖')
        .replaceAll('H', '𝓗')
        .replaceAll('I', '𝓘')
        .replaceAll('J', '𝓙')
        .replaceAll('K', '𝓚')
        .replaceAll('L', '𝓛')
        .replaceAll('M', '𝓜')
        .replaceAll('N', '𝓝')
        .replaceAll('O', '𝓞')
        .replaceAll('P', '𝓟')
        .replaceAll('Q', '𝓠')
        .replaceAll('R', '𝓡')
        .replaceAll('S', '𝓢')
        .replaceAll('T', '𝓣')
        .replaceAll('U', '𝓤')
        .replaceAll('V', '𝓥')
        .replaceAll('W', '𝓦')
        .replaceAll('X', '𝓧')
        .replaceAll('Y', '𝓨')
        .replaceAll('Z', '𝓩');
return QueenFont  
        
      
  }

      //|⬡═══════════════════// 35 //══════════════════════|❝ Ⓒ𝙰𝙻𝙸𝙴𝙽 𝙰𝙻𝙵𝙰 𝙱𝙾𝚃 𝙱𝚈 𝚃𝙾𝚇𝙸𝙲 𝙰𝙻𝙸𝙴𝙽™ ❞|═══════════════════════════════════════════⬡|//	

  function QueenFont35(textz)  {  
     QueenFont = textz
        .replaceAll('a', '𝔞')
        .replaceAll('b', '𝔟')
        .replaceAll('c', '𝔠')
        .replaceAll('d', '𝔡')
        .replaceAll('e', '𝔢')
        .replaceAll('f', '𝔣')
        .replaceAll('g', '𝔤')
        .replaceAll('h', '𝔥')
        .replaceAll('i', '𝔦')
        .replaceAll('j', '𝔧')
        .replaceAll('k', '𝔨')
        .replaceAll('l', '𝔩')
        .replaceAll('m', '𝔪')
        .replaceAll('n', '𝔫')
        .replaceAll('o', '𝔬')
        .replaceAll('p', '𝔭')
        .replaceAll('q', '𝔮')
        .replaceAll('r', '𝔯')
        .replaceAll('s', '𝔰')
        .replaceAll('t', '𝔱')
        .replaceAll('u', '𝔲')
        .replaceAll('v', '𝔳')
        .replaceAll('w', '𝔴')
        .replaceAll('x', '𝔵')
        .replaceAll('y', '𝔶')
        .replaceAll('z', '𝔷')
        .replaceAll('A', '𝔄')
        .replaceAll('B', '𝔅')
        .replaceAll('C', 'ℭ')
        .replaceAll('D', '𝔇')
        .replaceAll('E', '𝔈')
        .replaceAll('F', '𝔉')
        .replaceAll('G', '𝔊')
        .replaceAll('H', 'ℌ')
        .replaceAll('I', 'ℑ')
        .replaceAll('J', '𝔍')
        .replaceAll('K', '𝔎')
        .replaceAll('L', '𝔏')
        .replaceAll('M', '𝔐')
        .replaceAll('N', '𝔑')
        .replaceAll('O', '𝔒')
        .replaceAll('P', '𝔓')
        .replaceAll('Q', '𝔔')
        .replaceAll('R', 'ℜ')
        .replaceAll('S', '𝔖')
        .replaceAll('T', '𝔗')
        .replaceAll('U', '𝔘')
        .replaceAll('V', '𝔙')
        .replaceAll('W', '𝔚')
        .replaceAll('X', '𝔛')
        .replaceAll('Y', '𝔜')
        .replaceAll('Z', 'ℨ');
return QueenFont  
        
      
  }

      //|⬡═══════════════════// 36 //══════════════════════|❝ Ⓒ𝙰𝙻𝙸𝙴𝙽 𝙰𝙻𝙵𝙰 𝙱𝙾𝚃 𝙱𝚈 𝚃𝙾𝚇𝙸𝙲 𝙰𝙻𝙸𝙴𝙽™ ❞|═══════════════════════════════════════════⬡|//	

  function QueenFont36(textz)  {  
     QueenFont = textz
        .replaceAll('`', '`')
        .replaceAll('1', '１')
        .replaceAll('2', '２')
        .replaceAll('3', '３')
        .replaceAll('4', '４')
        .replaceAll('5', '５')
        .replaceAll('6', '６')
        .replaceAll('7', '７')
        .replaceAll('8', '８')
        .replaceAll('9', '９')
        .replaceAll('0', '０')
        .replaceAll('-', '－')
        .replaceAll('=', '＝')
        .replaceAll('~', '~')
        .replaceAll('!', '！')
        .replaceAll('@', '＠')
        .replaceAll('#', '＃')
        .replaceAll('$', '＄')
        .replaceAll('%', '％')
        .replaceAll('^', '^')
        .replaceAll('&', '＆')
        .replaceAll('*', '＊')
        .replaceAll('(', '（')
        .replaceAll(')', '）')
        .replaceAll('_', '_')
        .replaceAll('+', '＋')
        .replaceAll('q', 'ｑ')
        .replaceAll('w', 'ｗ')
        .replaceAll('e', 'ｅ')
        .replaceAll('r', 'ｒ')
        .replaceAll('t', 'ｔ')
        .replaceAll('y', 'ｙ')
        .replaceAll('u', 'ｕ')
        .replaceAll('i', 'ｉ')
        .replaceAll('o', 'ｏ')
        .replaceAll('p', 'ｐ')
        .replaceAll('[', '[')
        .replaceAll(']', ']')
        .replaceAll('\\', '\\')
        .replaceAll('Q', 'Ｑ')
        .replaceAll('W', 'Ｗ')
        .replaceAll('E', 'Ｅ')
        .replaceAll('R', 'Ｒ')
        .replaceAll('T', 'Ｔ')
        .replaceAll('Y', 'Ｙ')
        .replaceAll('U', 'Ｕ')
        .replaceAll('I', 'Ｉ')
        .replaceAll('O', 'Ｏ')
        .replaceAll('P', 'Ｐ')
        .replaceAll('{', '{')
        .replaceAll('  ', '  ')
        .replaceAll('|', '|')
        .replaceAll('a', 'ａ')
        .replaceAll('s', 'ｓ')
        .replaceAll('d', 'ｄ')
        .replaceAll('f', 'ｆ')
        .replaceAll('g', 'ｇ')
        .replaceAll('h', 'ｈ')
        .replaceAll('j', 'ｊ')
        .replaceAll('k', 'ｋ')
        .replaceAll('l', 'ｌ')
        .replaceAll(';', '；')
        .replaceAll('\'', '＇')
        .replaceAll('A', 'Ａ')
        .replaceAll('S', 'Ｓ')
        .replaceAll('D', 'Ｄ')
        .replaceAll('F', 'Ｆ')
        .replaceAll('G', 'Ｇ')
        .replaceAll('H', 'Ｈ')
        .replaceAll('J', 'Ｊ')
        .replaceAll('K', 'Ｋ')
        .replaceAll('L', 'Ｌ')
        .replaceAll(',', '：')
        .replaceAll('\"', '\"')
        .replaceAll('z', 'ｚ')
        .replaceAll('x', 'ｘ')
        .replaceAll('c', 'ｃ')
        .replaceAll('v', 'ｖ')
        .replaceAll('b', 'ｂ')
        .replaceAll('n', 'ｎ')
        .replaceAll('m', 'ｍ')
        .replaceAll(',', '，')
        .replaceAll('.', '．')
        .replaceAll('/', '／')
        .replaceAll('Z', 'Ｚ')
        .replaceAll('X', 'Ｘ')
        .replaceAll('C', 'Ｃ')
        .replaceAll('V', 'Ｖ')
        .replaceAll('B', 'Ｂ')
        .replaceAll('N', 'Ｎ')
        .replaceAll('M', 'Ｍ')
        .replaceAll('<', '<')
        .replaceAll('>', '>')
        .replaceAll('?', '？');
return QueenFont  
        
      
  }

    
  function QueenFont37(textz)  {  
     QueenFont = textz
        .replaceAll('a', 'ᴀ')
        .replaceAll('b', 'ʙ')
        .replaceAll('c', 'ᴄ')
        .replaceAll('d', 'ᴅ')
        .replaceAll('e', 'ᴇ')
        .replaceAll('f', 'ғ')
        .replaceAll('g', 'ɢ')
        .replaceAll('h', 'ʜ')
        .replaceAll('i', 'ɪ')
        .replaceAll('j', 'ᴊ')
        .replaceAll('k', 'ᴋ')
        .replaceAll('l', 'ʟ')
        .replaceAll('m', 'ᴍ')
        .replaceAll('n', 'ɴ')
        .replaceAll('o', 'ᴏ')
        .replaceAll('p', 'ᴘ')
        .replaceAll('q', 'ǫ')
        .replaceAll('r', 'ʀ')
        .replaceAll('s', 's')
        .replaceAll('t', 'ᴛ')
        .replaceAll('u', 'ᴜ')
        .replaceAll('v', 'ᴠ')
        .replaceAll('w', 'ᴡ')
        .replaceAll('x', 'x')
        .replaceAll('y', 'ʏ')
        .replaceAll('z', 'ᴢ')
        .replaceAll('A', 'ᴀ')
        .replaceAll('B', 'ʙ')
        .replaceAll('C', 'ᴄ')
        .replaceAll('D', 'ᴅ')
        .replaceAll('E', 'ᴇ')
        .replaceAll('F', 'ғ')
        .replaceAll('G', 'ɢ')
        .replaceAll('H', 'ʜ')
        .replaceAll('I', 'ɪ')
        .replaceAll('J', 'ᴊ')
        .replaceAll('K', 'ᴋ')
        .replaceAll('L', 'ʟ')
        .replaceAll('M', 'ᴍ')
        .replaceAll('N', 'ɴ')
        .replaceAll('O', 'ᴏ')
        .replaceAll('P', 'ᴘ')
        .replaceAll('Q', 'ǫ')
        .replaceAll('R', 'ʀ')
        .replaceAll('S', 's')
        .replaceAll('T', 'ᴛ')
        .replaceAll('U', 'ᴜ')
        .replaceAll('V', 'ᴠ')
        .replaceAll('W', 'ᴡ')
        .replaceAll('X', 'x')
        .replaceAll('Y', 'ʏ')
        .replaceAll('Z', 'ᴢ');
return QueenFont  
        
      
  }

  function QueenFont38(textz)  {  
     QueenFont = textz
        .replaceAll('a', '𝒂')
        .replaceAll('b', '𝒃')
        .replaceAll('c', '𝒄')
        .replaceAll('d', '𝒅')
        .replaceAll('e', '𝒆')
        .replaceAll('f', '𝒇')
        .replaceAll('g', '𝒈')
        .replaceAll('h', '𝒉')
        .replaceAll('i', '𝒊')
        .replaceAll('j', '𝒋')
        .replaceAll('k', '𝒌')
        .replaceAll('l', '𝒍')
        .replaceAll('m', '𝒎')
        .replaceAll('n', '𝒏')
        .replaceAll('o', '𝒐')
        .replaceAll('p', '𝒑')
        .replaceAll('q', '𝒒')
        .replaceAll('r', '𝒓')
        .replaceAll('s', '𝒔')
        .replaceAll('t', '𝒕')
        .replaceAll('u', '𝒖')
        .replaceAll('v', '𝒗')
        .replaceAll('w', '𝒘')
        .replaceAll('x', '𝒙')
        .replaceAll('y', '𝒚')
        .replaceAll('z', '𝒛')
        .replaceAll('A', '𝐴')
        .replaceAll('B', '𝐵')
        .replaceAll('C', '𝐶')
        .replaceAll('D', '𝐷')
        .replaceAll('E', '𝐸')
        .replaceAll('F', '𝐹')
        .replaceAll('G', '𝐺')
        .replaceAll('H', '𝐻')
        .replaceAll('I', '𝐼')
        .replaceAll('J', '𝐽')
        .replaceAll('K', '𝐾')
        .replaceAll('L', '𝐿')
        .replaceAll('M', '𝑀')
        .replaceAll('N', '𝑁')
        .replaceAll('O', '𝑂')
        .replaceAll('P', '𝑃')
        .replaceAll('Q', '𝑄')
        .replaceAll('R', '𝑅')
        .replaceAll('S', '𝑆')
        .replaceAll('T', '𝑇')
        .replaceAll('U', '𝑈')
        .replaceAll('V', '𝑉')
        .replaceAll('W', '𝑊')
        .replaceAll('X', '𝑋')
        .replaceAll('Y', '𝑌')
        .replaceAll('Z', '𝑍');
return QueenFont  
        
      
  }

  function QueenFont39(textz)  {  
     QueenFont = textz
        .replaceAll('a', '𝛥')
        .replaceAll('b', '𝐵')
        .replaceAll('c', '𝐶')
        .replaceAll('d', '𝐷')
        .replaceAll('e', '𝛯')
        .replaceAll('f', '𝐹')
        .replaceAll('g', '𝐺')
        .replaceAll('h', '𝛨')
        .replaceAll('i', '𝛪')
        .replaceAll('j', '𝐽')
        .replaceAll('k', '𝛫')
        .replaceAll('l', '𝐿')
        .replaceAll('m', '𝛭')
        .replaceAll('n', '𝛮')
        .replaceAll('o', '𝛩')
        .replaceAll('p', '𝛲')
        .replaceAll('q', '𝑄')
        .replaceAll('r', '𝑅')
        .replaceAll('s', '𝑆')
        .replaceAll('t', '𝑇')
        .replaceAll('u', '𝑈')
        .replaceAll('v', '𝛻')
        .replaceAll('w', '𝑊')
        .replaceAll('x', '𝛸')
        .replaceAll('y', '𝑌')
        .replaceAll('z', '𝛧')
        .replaceAll('A', '𝛥')
        .replaceAll('B', '𝐵')
        .replaceAll('C', '𝐶')
        .replaceAll('D', '𝐷')
        .replaceAll('E', '𝛯')
        .replaceAll('F', '𝐹')
        .replaceAll('G', '𝐺')
        .replaceAll('H', '𝛨')
        .replaceAll('I', '𝛪')
        .replaceAll('J', '𝐽')
        .replaceAll('K', '𝛫')
        .replaceAll('L', '𝐿')
        .replaceAll('M', '𝛭')
        .replaceAll('N', '𝛮')
        .replaceAll('O', '𝛩')
        .replaceAll('P', '𝛲')
        .replaceAll('Q', '𝑄')
        .replaceAll('R', '𝑅')
        .replaceAll('S', '𝑆')
        .replaceAll('T', '𝑇')
        .replaceAll('U', '𝑈')
        .replaceAll('V', '𝛻')
        .replaceAll('W', '𝑊')
        .replaceAll('X', '𝛸')
        .replaceAll('Y', '𝑌')
        .replaceAll('Z', '𝛧');
return QueenFont  
        
      
  }

   
